### ISSUE TITLE
feature: Add support for Neovim's native LSP semantic tokens

### ISSUE THREAD

**Issue by XXiaoA** [rose-pine/neovim#107]
Now nvim nightly support semantic token  https://github.com/neovim/neovim/pull/21100

References: https://github.com/sainnhe/gruvbox-material/pull/162

**Comment by mvllow** [comment]
Is this different from #101?

**Comment by XXiaoA** [comment]
Yeah OFC. There are some differences. Now if i use semantic token. My eyes are captured by the purple

![VID_20230109_081816_147](https://user-images.githubusercontent.com/62557596/211226288-e7a83db2-d59f-482f-bdfb-1e1398f49958.gif)

This experience is really bad
