### ISSUE TITLE
Editing html tags color

### ISSUE THREAD

**Issue by Sebasssssss** [rose-pine/neovim#109]
Hi, I have been trying to edit the html tags so they look like the function color (pine), but I am not getting it. I try to edit line 136 in /lua/rose-pine/theme.lua, in the html tags section, but I am not getting the color that i want. Is there any way to do it?

**Comment by mvllow** [comment]
You can overwrite these highlights in the config:

```lua
use({
	'rose-pine/neovim',
	as = 'rose-pine',
	config = function()
		require('rose-pine').setup({
			highlight_groups = {
				['@tag'] = { fg = 'pine' }
			}
		})
		vim.cmd.colorscheme('rose-pine')
	end,
})
```

`@tag` is the new treesitter highlight group for html tags and work on Neovim nightly. Otherwise, `TSTag` may work if I remember correctly.

**Comment by Sebasssssss** [comment]
beautiful! Works excelent, thank you very much!
