### ISSUE TITLE
Kitty config for this theme?

### ISSUE THREAD

**Issue by jim-at-jibba** [rose-pine/neovim#11]
I dont suppose you have kitty of alacritty config for this theme its lovely!

Thanks

**Comment by mvllow** [comment]
I assume you closed this because you found them but just in case: [kitty](https://github.com/rose-pine/kitty) and [alacritty](https://github.com/rose-pine/alacritty)

Enjoy!

**Comment by jim-at-jibba** [comment]
I did, thanks.
