### ISSUE TITLE
Readme install doesn't work

### ISSUE THREAD

**Issue by master-of-zen** [rose-pine/neovim#112]
Lunar vim.
I use packer for install.
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```
✗ rose-pine/neovim: failed to update
```

## Config code
```
{
    'rose-pine/neovim',
    as = 'rose-pine',
    config = function()
        vim.cmd('colorscheme rose-pine')
    end
}
```
![2023 01 05_23:11:26](https://user-images.githubusercontent.com/46526140/210880748-d6b6cf05-9457-4a38-98c2-b6504486165e.png)

**Comment by mvllow** [comment]
I've ran into this issue with a few plugins and I think it has to do with force pushing a commit or similar. Removing the `rose-pine` folder and re-installing should do the trick :)

```sh
rm -rf ~/.local/share/nvim/site/pack/packer/start/rose-pine/
```

**Comment by master-of-zen** [comment]
> ```shell
> rm -rf ~/.local/share/nvim/site/pack/packer/start/rose-pine/
> ```

^ doesn't fixed the issue, full reinstall - worked.
