### ISSUE TITLE
[Feature Request] Expand user config to also deal with user specified style (bold / italics) setting

### ISSUE THREAD

**Issue by janislaus** [rose-pine/neovim#113]
Hi,
great theme. It would be great to also be able to specify the style (bold / italic) for text in the setup function. 

It already works, if the given highlight group does not already have a specified style. However, if for example the following is passed to the setup function:
`    
highlight_groups = {
        ['@method'] = { bg = 'rose', style = 'bold'},
        ...
}
`
Here `'@method'` is already in italics. The result is, that `'@method'` will be both italic and bold.

**Desired behavior:**
The style specified by the user takes precedence over the preconfigured style.

**Comment by mvllow** [comment]
I'm curious if moving to the newer highlight api would solve this, e.g:

```diff
- ['@method'] = { bg = 'rose', style = 'bold' }
+ ['@method'] = { bg = 'rose', bold = true, italic = false }
```

In the example above I explicitly disabled italic but I'm actually not sure if that would be necessary or not. Will play around with it though :)

**Comment by mvllow** [comment]
Highlight api has been updated on the canary branch. Your overrides should now replace existing highlights entirely, e.g:

```lua
require("rose-pine").setup({
  highlight_groups = {
    -- No longer matters if italic was previously enabled.
    ["@method"] = { bg = "rose", bold = true },
  },
})
```

Be sure to use the canary branch for now:

```lua
{
  "rose-pine/neovim",
  branch = "canary",
}
```

**Comment by janislaus** [comment]
Thanks for the fix. The canary branch does exactly what I wanted ;)
