### ISSUE TITLE
bug: Rosé Pine Dawn hard to read `diffview.nvim` history view

### ISSUE THREAD

**Issue by briandipalma** [rose-pine/neovim#118]
Using https://github.com/sindrets/diffview.nvim and Rosé Pine Dawn is a bit awkward on the eye. I've tested this in Kitty and another terminal so I think it's the theme:

![image](https://user-images.githubusercontent.com/1597820/212329568-d04d51e8-8643-4be4-b80b-87f6730c91b2.png)

The yellow, the bold cyan and the white text are hard to read. Is there anything that can be done to improve this?

**Comment by mvllow** [comment]
Hmm, unable to reproduce this. Do you have a minimal config to replicate this?

Example repro:

```lua
-- DO NOT change the paths and do not remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- Set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy.nvim
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
  "rose-pine/neovim.nvim",
  config = function()
    -- Add relevant Rosé Pine config below
    require("rose-pine").setup({})
  end,
  "sindrets/diffview.nvim",
  config = true
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("rose-pine")
-- Add anything else here
```

**Comment by briandipalma** [comment]
Yeah looks great with nothing installed:

![image](https://user-images.githubusercontent.com/1597820/213025769-32bf0e21-f7c5-4aa7-9ebc-0f96a6ce15ec.png)

```
-- DO NOT change the paths and do not remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- Set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy.nvim
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
  "rose-pine/neovim",
  config = function()
    -- Add relevant Rosé Pine config below
    require("rose-pine").setup({})
  end,
  "sindrets/diffview.nvim",
  config = true,
  'nvim-lua/plenary.nvim',
  'nvim-tree/nvim-web-devicons'
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("rose-pine")
-- Add anything else here
```

How does it select the Dawn variant? Is it the default?

**Comment by briandipalma** [comment]
OK I found the issue, I had

```lua
vim.cmd("set background=light")
```

in my rose-pine config which seemed to cause the problem.
I added 

```
Variant respects vim.o.background, using dawn when light and dark_variant when dark
```

to the README which no longer seems to be the case, will I rephrase it or delete it?

**Comment by briandipalma** [comment]
OK, the only issue is the dark variant quickly flashes when I start neovim before changing to the Dawn variant...so I guess the light background setting did do one useful thing. Is there any way I can pass in a configuration setting to enable Dawn from start? I'm guessing at the moment the variant is changed because the theme somehow knows my terminal has a light colour theme selected?

**Comment by mvllow** [comment]
We may implement separate themes for each variant, e.g. `:colorscheme rose-pine-dawn`; follow our [canary branch](https://github.com/rose-pine/neovim/pull/114) for updates on that.

At the moment, early in your vim config, set `vim.opt.background = "light"` to hopefully prevent any flicker :)

**Comment by briandipalma** [comment]
I've subscribed to #98.

> At the moment, early in your vim config, set vim.opt.background = "light"

That causes this issue, even when added early in my config. I can live with a flicker.
Without that config though the `gitcommit` message panel is dark though.

![image](https://user-images.githubusercontent.com/1597820/213169317-d69cd24b-e4bd-462e-aac6-9af0558f37b3.png)

Which is really quite odd.
