### ISSUE TITLE
feature: Add support for noice plugin because the cursor is hidden.

### ISSUE THREAD

**Issue by bassamsdata** [rose-pine/neovim#121]
### Is your feature request related to a problem? Please describe.

Yes, the cursor is hidden with the plugin `"folke/noice.nvim"` Can't see where my cursor is.

https://user-images.githubusercontent.com/105807570/214621124-968551fe-273a-422a-8c5d-4d6c56291cba.mov

### Describe the solution you'd like

just to show then normal cursor in the noice command line ui.

I'd like to suggest if possible to support this plugin since I think many people will use it from now so on due to LazyVim repo is using it as default.

Appreciate any support and thank you

### Describe alternatives you've considered

Well I don't have 

### Additional context

I tried the `noice` with `default` config for rose-pine and with `transparent` background but it's the same output.

Thank you for this amazing theme.

**Comment by mvllow** [comment]
Thanks for the report! I pushed a fix to the canary branch but you could also add this to your Rosé Pine setup:

```lua
highlight_groups = {
	-- Match cursor if using Rosé Pine as your terminal theme.
	Cursor = { fg = 'text', bg = 'highlight_high' }
}
```

**Comment by bassamsdata** [comment]
thank you for the fix. Updated the canary branch and the issue solved.
