### ISSUE TITLE
bug: disable_float_background no longer work with floating code completion in the 4eac261 (latest) commit 

### ISSUE THREAD

**Issue by tin-pham** [rose-pine/neovim#124]
### Neovim version (nvim -v)

0.8.3

### Terminal

Alacrity

### Describe the bug

It work just fine in 845a6ad commit

The dim_nc_background still work, so in right panel it background removed
![image](https://user-images.githubusercontent.com/20679090/220788673-a65892eb-9939-4810-a400-a3b7a13a86aa.png)

Other floating background work just fine

![image](https://user-images.githubusercontent.com/20679090/220789422-47952b7e-7c78-4d05-8fce-bb323c589cdd.png)

I revert to 845a6ad commit and it work like charm
![image](https://user-images.githubusercontent.com/20679090/220795905-2f56d07b-3641-42a0-9b57-83a8ea13de4a.png)

Extra: why color now look worse in 4eac261 commit
![image](https://user-images.githubusercontent.com/20679090/220795029-50a463f9-859e-4916-be9f-c7ae07cd380a.png)

Back then: 
![image](https://user-images.githubusercontent.com/20679090/220796461-ce6785d8-8b0d-4a09-9f35-665ee0a2cb19.png)

        
      

### Steps To Reproduce

1. Install latest 4eac261 commit of rose-pine/neovim
2. Turn on disable_float_background

### Expected Behavior

1. Code completion window background not remove

**Comment by mvllow** [comment]
Thanks for pointing these out. I will take a look at the floats asap but as far as the colours being "worse", please provide the output of `:Inspect` for the interface keys and I'll revert the change :)
