### ISSUE TITLE
bug: panel setting in groups is not working

### ISSUE THREAD

**Issue by dov0p** [rose-pine/neovim#128]
### Neovim version (nvim -v)

0.8.3

### Terminal

windows terminal

### Describe the bug

`panel` setting in `groups` is not working

### Steps To Reproduce

I change the color of `panel` in `groups` but it's not working. It used to work before update.

### Expected Behavior

In `theme.lua`, `maybe` uses colors in `palette` instead of colors in `groups`.
I think it's nice to add `nc` in `groups` in case I want to adjust the `nc` color.

**Comment by mvllow** [comment]
Fixed via #130 (hopefully). Feel free to use the canary branch or wait for canary to be merged into main :)
