### ISSUE TITLE
Vertical Split Column

### ISSUE THREAD

**Issue by ovidius72** [rose-pine/neovim#13]
When I do a vertical Split I see a gray column like in the screenshot below. Is there a way to make it the same color of the background? Or Maybe a thin line just a little bit darken than the background? 
I think those are the foldercolumn.

Thanks.

![theme_lua_____config_nvim_plugged_github-nvim-theme_lua_github-theme__-_NVIM](https://user-images.githubusercontent.com/3592928/129493574-51a0d2a6-8b74-4d18-9013-df8af9a01414.png)

**Comment by mvllow** [comment]
Thanks for the report ☺️ Haven't used `FoldColumn` personally so not sure if it needs a foreground set but went ahead and made it the same background colour as the editor.
