### ISSUE TITLE
RFC: Options and groups

### ISSUE THREAD

**Issue by mvllow** [rose-pine/neovim#131]
Currently there is some overlap between `groups` and `highlight_groups`, as well as some of our options.

## Options

My initial thought is to deprecate the options below in favour of improving groups and contributing to https://github.com/rose-pine/neovim/wiki/Recipes.

**bold_vert_split**

```lua
{
	bold_vert_split = true,
	
	-- Is equal to

	highlight_groups = {
		VertSplit = { fg = "highlight_med", bg = "highlight_med" }
	}
}
```

**dim_nc_background**

We'll come back to this in the future.

## Groups

Groups have proven to be quite beneficial for customising Rosé Pine.

```lua
{
	groups = {
		comment = "foam"
	},

	-- Is equal to

	highlight_groups = {
		Comment = { fg = "foam" },

		-- Highlight groups give the user more control
		Comment = { fg = "foam", bg = "foam", blend = 10, italic = true }
	},
}
```

I think it makes sense to deprecate duplicate groups:

1. **groups.base**

	Setting `groups.base = "none"` seems like the only useful override but can also be achieved via `disable_background = true`

2. **groups.panel**

	Similar to `groups.base`, removable via `disable_float_background = true`
	
3. **groups.base_nc and groups.panel_nc**

	need some more thought
	
4. **groups.border**

	Slightly more discoverable, but if we linked all borders to `FloatBorder` we could replace it with:

	```diff
	- groups.border = "highlight_med"
	+ highlight_groups["FloatBorder"] = { fg = "highlight_med", bg = "surface" }
	```

5. **groups.comment**

	```diff
	- groups.comment = "muted"
	+ highlight_groups["Comment"] = { fg = "muted" }
	```

6. **groups.link**

	```diff
	- groups.link = "iris"
	+ highlight_groups["@text.uri"] = { fg = "iris", sp = "iris", underline = true }
	```

7. **groups.punctuation**

	```diff
	- groups.punctuation = "subtle"
	+ highlight_groups["@punctuation"] = "subtle"
	```

## Closing thoughts

Mainly thinking out loud here. Having so many options for a theme feels silly. Open to any feedback and suggestions.

More highlights can be linked to similar existing highlights for proposals to be more viable.

**Comment by mvllow** [comment]
I'm leaning against changing points 4-7. After some testing, relying on arbitrary highlight groups such as `@text.uri` to change all links does not seem intuitive. Need to put some more thought into this to see if any meaninful changes and simplifications can be made to justify any breaking changes (any deprecated options should be gracefully handled).

**Comment by mvllow** [comment]
That would be ideal, because you have more flexibility when setting `highlight_groups` whereas `groups` would contain anything that changes multiple highlight groups, e.g punctuation.

If these changes are made, I don’t think I would remove any previously working options but simply remove them from any documentation to avoid breaking changes.

**Comment by NiamhFerns** [comment]
Yeah I think that would absolutely be a good change. 

One thing that would be nice as well is if highlight_groups could maintain their default behaviour for untouched options when being changed. 

If I only want to, for example, enable italics on paramaters but not touch the default colour, currently I have to do `["@parameter"] = { fg = "iris", italic = true },` for it to maintain the colour set by rose pine. It would be nice if I could just change one aspect of a highlight_group without it changing all the others unintentionally. This means that `["@parameter"] = { italic = true },` would only enable highlights but not touch the default colours or whether it's bold or not.

**Comment by NiamhFerns** [comment]
> One thing that would be nice as well is if highlight_groups could maintain their default behaviour for untouched options when being changed.
>
> If I only want to, for example, enable italics on paramaters but not touch the default colour, currently I have to do `["@parameter"] = { fg = "iris", italic = true },` for it to maintain the colour set by rose pine. It would be nice if I could just change one aspect of a highlight_group without it changing all the others unintentionally. This means that `["@parameter"] = { italic = true },` would only enable highlights but not touch the default colours or whether it's bold or not.

PR for this is now up. pull #171
