### ISSUE TITLE
Hot reload lualine theme when variant changes

### ISSUE THREAD

**Issue by VergeDX** [rose-pine/neovim#14]
Hi, I am a user of macOS. My system support auto light & dark mode switch.
So I'm writing a script to match the system theme, by using the vim command:
`:lua require('rose-pine.functions').select_variant('dawn')` at running time.

But I noticed that command will only change the theme of the editor,
the lualine theme still keeps the original...

I'm a noob of vim and Lua, I think I do not refresh the lualine theme correctly.
Could you please give me some advice...? Thank you very much : )

**Comment by mvllow** [comment]
Unfortunately the author of lualine has said hot reloading is not currently possible in [this issue](https://github.com/hoob3rt/lualine.nvim/issues/230#issuecomment-843680942). There may some workaround of course but after some testing I was unable to get anything working. Happy to accept a PR if someone knows how to add this 😌

**Comment by VergeDX** [comment]
Thanks for your patient. I also found this fork : )

The way I switch between is using neovim's signal handler, not running the command directly in neovim.
Directly running the command to switch theme at inner neovim is works fine,
but shows this bug in neovim's signal handler.

The issue I meet seems caused by neovim itself, not your perfect theme or lualine : )
