### ISSUE TITLE
Update supported plugins list in Wiki

### ISSUE THREAD

**Issue by mrtnvgr** [rose-pine/neovim#142]
New plugins are:

- [healthcheck](https://neovim.io/doc/user/pi_health.html#health-dev)
- [LSP Semantic Token Groups](https://neovim.io/doc/user/lsp.html#lsp-semantic-highlight)
- [vim.lsp.buf.document_highlight()](https://neovim.io/doc/user/lsp.html#lsp-highlight)
- [lsp-highlight-codelens](https://neovim.io/doc/user/lsp.html#lsp-highlight-codelens)
- [neo-tree.nvim](https://github.com/nvim-neo-tree/neo-tree.nvim)
- [vimwiki](https://github.com/vimwiki/vimwiki)
- [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim)
- [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)
- [leap.nvim](https://github.com/ggandor/leap.nvim)
- [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui)
- [dashboard.nvim](https://github.com/glepnir/dashboard-nvim)
- [nvim-navic](https://github.com/SmiteshP/nvim-navic)
- [noice.nvim](https://github.com/folke/noice.nvim)
- [mini.indentscope](https://github.com/echasnovski/mini.indentscope) (#144)

**Comment by mrtnvgr** [comment]
I think it would be better if the wiki was in the repository. (i.e. in the `.wiki` folder). Contributors would be able to update the list themselves and suggest new recipes.

**Comment by mvllow** [comment]
Thank you for compiling this list, super helpful! I'm happy to copy them myself to the wiki but I did make the wiki (hopefully) editable by anyone :)

**Comment by mrtnvgr** [comment]
[2061ef3](https://github.com/rose-pine/neovim/wiki/Home/2061ef34ddee2034416a04a969527b95d553c23e)
