### ISSUE TITLE
feature:  Shade to work with NvimTree

### ISSUE THREAD

**Issue by ebiscaia** [rose-pine/neovim#147]
I would like that the shading that is applied when the option dim_nc_background=true to work also with NvimTree. Sometimes I got lost because I think I am in the main window and start typing just to realise that I am in the tree.

Best regards,

Eduardo

**Comment by mvllow** [comment]
The editor window should be dimmed if you are inside NvimTree already, is this not your experience?

**Comment by ebiscaia** [comment]
The problem is NvimTree never shades. Sorry for causing the confusion.

**Comment by mvllow** [comment]
No worries, that makes sense. Changing this would be a breaking change for some – so maybe I'll group this with other breaking changes in the future. Until then, try:

```lua
require("rose-pine").setup({
  highlight_groups = {
    NvimTreeNormalNC = { bg = "nc" },
  }
})
```

_Note: Update to the latest version of Rosé Pine to use the named colour "nc"_

**Comment by ebiscaia** [comment]
Great,

That is what I was looking for. Maybe it is not necessary to change it, just something in the README so that other can apply the same change if they want to.

Thanks again,

Eddie
