### ISSUE TITLE
bug: Tab numbers are very faint in Dawn using bufferline

### ISSUE THREAD

**Issue by briandipalma** [rose-pine/neovim#149]
### Neovim version (nvim -v)

NVIM v0.8.3

### Terminal

kitty

### Describe the bug

The selected tab number is faint with the Dawn variant.

![image](https://user-images.githubusercontent.com/1597820/228900554-9f8b9908-f109-4079-81aa-ec81aa02b799.png)

### Steps To Reproduce

1. LazyVim with rose-pine Dawn variant.

### Expected Behavior

Darker text?

### Repro

```Lua
Can't get the numbers to show up on a simple config...
```

**Comment by mvllow** [comment]
> Can't get the numbers to show up on a simple config...

Please provide a reproduction or at least the tabline configuration (plugin used, etc.)

**Comment by briandipalma** [comment]
Yes it does, thanks!
![image](https://user-images.githubusercontent.com/1597820/228951948-28627eb6-0c3f-4610-8393-a9fa2d12b3ac.png)
