### ISSUE TITLE
bug: indent lines using indent-blankline get italicized

### ISSUE THREAD

**Issue by JNer1** [rose-pine/neovim#153]
### Neovim version (nvim -v)

0.8.3

### Terminal

iTerm2

### Describe the bug

When the font gets italicized, the indent lines get italicized as well. This does not seem to affect comments from my testing.

It seems to require adding `nocombine = true` to the highlight groups.

Please see [https://github.com/lukas-reineke/indent-blankline.nvim/issues/72](https://github.com/lukas-reineke/indent-blankline.nvim/issues/72)

and [https://github.com/folke/tokyonight.nvim/pull/247](https://github.com/folke/tokyonight.nvim/pull/247)

<img width="642" alt="image" src="https://user-images.githubusercontent.com/98091622/231480431-6a32cffa-4f62-452b-848c-28b2cdc80bdb.png">

### Steps To Reproduce

1. Have a block of code wherein the text gets italicized, such as destructing a JavaScript object as shown in my screenshot.
2. Make sure the block has at least one indent level and spans more than one line.
3. See the indent lines get italicized as well

### Expected Behavior

Indent lines should stay straight, or unitalicized.

### Repro

```Lua
-- DO NOT change the paths and do not remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- Set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy.nvim
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {
  "rose-pine/neovim",
  name = "rose-pine",
  config = function()
    -- Add relevant Rosé Pine config below
    require("rose-pine").setup({})
  end,
  "lukas-reineke/indent-blankline.nvim",
  config = function()
    require("indent_blankline").setup {
    char = '┊',
}
  end
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("rose-pine")
-- Add anything else here
```

**Comment by mvllow** [comment]
Thank you for the detailed report :) I'll merge the associated PR
