### ISSUE TITLE
bug: wrong colors in telescope git file diff preview

### ISSUE THREAD

**Issue by alsmnn** [rose-pine/neovim#156]
### Neovim version (nvim -v)

v0.8.2

### Terminal

Konsole

### Describe the bug

When i open the git status with telescope (telescope.builtin.git_status) the same color is used for removed and for added lines.
![rose-pine-treesitter-git-status](https://user-images.githubusercontent.com/32334619/234277953-5450c050-0860-4857-85bf-f3654fe9829c.png)

### Steps To Reproduce

1. Create a dir under /tmp
```
mkdir -p /tmp/nvim-test
```
2. git init inside `nvim-test`
3. add repro.lua 
4. install telescope and rose-pine
5. inside nvim run :
```
:lua require("telescope.builtin").git_status()
```
6. Have a look at the "Git File Diff Preview" 

### Expected Behavior

Added lines appear green and removed lines appear red as you can see in the screenshot with the colorscheme astrodark from [AstroNvim](https://github.com/AstroNvim/AstroNvim)
![astrodark-treesitter-git-status](https://user-images.githubusercontent.com/32334619/234277997-fe2689d9-e9aa-49d5-9494-e7cf28fec2f4.png)

### Repro

```Lua
-- DO NOT change the paths and do not remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- Set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy.nvim
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install plugins
local plugins = {{
  "rose-pine/neovim",
  name = "rose-pine",
  config = function()
    -- Add relevant Rosé Pine config below
    require("rose-pine").setup({})
  end
},
{"nvim-telescope/telescope.nvim",
  tag = "0.1.1",
  dependencies = { "nvim-lua/plenary.nvim" },
}}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("rose-pine")
-- Add anything else here
```

**Comment by mvllow** [comment]
Thank you for the detailed report! I'll try to look into this asap :)

**Comment by mvllow** [comment]
Apologies for the delay. It looks like the Rosé Pine neovim theme is actually not applying (perhaps you are using Rosé Pine for your terminal?). I did have to update the `vim.cmd.colorscheme` as that didn't work for some reason:

```diff
vim.cmd.colorscheme("rose-pine")
vim.cmd("colorscheme rose-pine")
```

Let me know if that fixes it for you :)

**Comment by alsmnn** [comment]
Good catch, yes I am using rose-pine for my terminal.
I played arround with it just yet and I don't have to change anything anymore to see the expected colors.
![rose-pine-newly-tried](https://user-images.githubusercontent.com/32334619/235859765-88beca95-e44c-4cb5-b745-9ad0de22f715.png)
