### ISSUE TITLE
feature: Variable and method color should look difference in js/ts

### ISSUE THREAD

**Issue by tin-pham** [rose-pine/neovim#164]
### Is your feature request related to a problem? Please describe.

Currently it look like this 
![image](https://github.com/rose-pine/neovim/assets/20679090/867ae5cc-125e-4d35-9681-80868784431d)

![image](https://github.com/rose-pine/neovim/assets/20679090/568b6766-12ff-497b-86ae-0e775c69117c)

### Describe the solution you'd like

make it difference

### Describe alternatives you've considered

Everything look great except when an object call a method, those 2 look the same 
![image](https://github.com/rose-pine/neovim/assets/20679090/840b37e7-69f1-4bc6-a3c9-1efe7fcf327d)

### Additional context

Great colorscheme, i already use it for 2 year

**Comment by mvllow** [comment]
To clarify, in the example below, would changing `exampleMethod` from iris to foam solve your issue?

**Before**

<img width="544" alt="Before screenshot of pseudo code demonstrating Rosé Pine colours—particularly `exampleMethod` and `options` names as iris." src="https://github.com/rose-pine/neovim/assets/1474821/68b686c5-24d2-4bb5-98be-bbceb621326f">

**After**

<img width="544" alt="After screenshot of pseudo code demonstrating Rosé Pine colours—particularly `exampleMethod` name as foam." src="https://github.com/rose-pine/neovim/assets/1474821/c7ae492b-c8f1-4f65-b6a1-1a7044017722">

**Comment by tin-pham** [comment]
Yes that look great.

**Comment by tin-pham** [comment]
Also interface look a little bit plain imo 
![image](https://github.com/rose-pine/neovim/assets/20679090/05bc33e8-1689-47a2-b2be-9b34c3d7d505)

**Comment by tin-pham** [comment]
Sorry if i give so many thing at once
![image](https://github.com/rose-pine/neovim/assets/20679090/e8354f85-2cbe-427f-88c8-a00fb84ad1dc)
