### ISSUE TITLE
Lsp_signature support

### ISSUE THREAD

**Issue by danymat** [rose-pine/neovim#17]
I don't know if it's possible to do, but lsp_signature is quite weird with rose-pine. I would love true rose pine support for it.

Btw, can you for your wonderful work, I use rose pine dawn daily and fully ! Such a beautiful color scheme .

**Comment by mvllow** [comment]
Appreciate the kind words 🥰

Here's what I _think_ you are looking at so please correct me if I'm wrong:

<img width="705" alt="Screen Shot 2021-08-24 at 12 38 45" src="https://user-images.githubusercontent.com/1474821/130663909-5629e4f4-7cb8-4ab6-8969-02c254a82965.png">

I'd love an example of what you're thinking of as far as how you want it to look. Thanks!

**Comment by danymat** [comment]
It does look like this with Dawn variant

<img width="1186" alt="Capture d’écran 2021-08-24 à 21 46 23" src="https://user-images.githubusercontent.com/5306901/130680044-58b1cc41-e0da-4949-a42f-5470bb6b40cb.png">

You can see that the border is very subtle, I think it could be nicer if it is with a primary dark color, don't you think?

**Comment by mvllow** [comment]
Increased the contrast a bit of `FloatBorder`, hope that's what you had in mind 😌

**Comment by danymat** [comment]
Yes it is a lot cooler, thank you !!
(Be sure that I do love this colorscheme)

<img width="1115" alt="Capture d’écran 2021-08-24 à 23 27 43" src="https://user-images.githubusercontent.com/5306901/130692493-836dc5fc-18d1-43bb-b1af-4a475856a44a.png">
