### ISSUE TITLE
feature: opportunity to change palette

### ISSUE THREAD

**Issue by kaiphat** [rose-pine/neovim#184]
### Is your feature request related to a problem? Please describe.

For me text color too white:) I want to change it directly and not to find all highlight groups for it.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by mvllow** [comment]
I'm not sure I want to expose every palette value to be overridden. This leads to some complexity related to automatic light/dark variants.

I will add _something_, however, that allows this behaviour. Sorry this has taken some time to get to, busy time of the year ~

**Comment by kaiphat** [comment]
> I'm not sure I want to expose every palette value to be overridden. This leads to some complexity related to automatic light/dark variants.
Yes, but it will be my problem:)

> Sorry this has taken some time to get to, busy time of the year ~
Oh, don't worry. I hope you feel better.

**Comment by itsFrank** [comment]
FYI as a workaround you can use `package.preload` to change the value of any specific color when the palette is loaded.

**Caveat** do not expect this behavior to be stable across versions, the author is free to break this at any time. 

I personally love the main theme but find the color for pine to have a bit too low contrast, so I lightened it by 15% using this technique:

```lua
{
    "rose-pine/neovim",
    name = "rose-pine",
    priority = 1000,
    config = function()
        local rose_pine_palette = require("rose-pine.palette")
        rose_pine_palette["pine"] = "#3d90b2"
        -- here we change what gets returned by requiring "rose-pine.palette" moving forward
        package.preload["rose-pine.palette"] = function()
            print("hello from preload")
                return rose_pine_palette
            end
    end,
}
```

**Comment by mvllow** [comment]
Clever solution @itsFrank. If that works for you, no need to change it but feel free to try out the canary branch as well. The release notes mention a way to change each color via a `before_highlight` hook.

Would love any feedback on canary as well :)

**Comment by kaiphat** [comment]
@itsFrank you are genius)

**Comment by itsFrank** [comment]
@mvllow super cool, this does indeed offer a nice solution. The following code has the same effect as my preload hack:
```lua
require("rose-pine").setup({
    before_highlight = function(group, highlight, palette)
        if highlight.fg == palette.pine then
            highlight.fg = "#419abe"
        end
    end,
})
```
