### ISSUE TITLE
bug: `gitsigns` background is not transparent when `disable_background` is set

### ISSUE THREAD

**Issue by jamestansx** [rose-pine/neovim#186]
### Neovim version (nvim -v)

NVIM v0.9.4

### Terminal

alacritty

### Describe the bug

`Gitsigns` related background doesn't consistent with other sign column symbols as the `bg` is set to `groups.background`. 

https://github.com/rose-pine/neovim/blob/92762f4fa2144c05db760ea254f4c399a56a7ef5/lua/rose-pine/theme.lua#L328-L330

It will be nice to make it consistent with `signcolumn` background.

### Steps To Reproduce

None

### Expected Behavior

`Gitsigns` background should  be similar to `Signcolumn` background

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({
  -- ADD ROSÉ PINE CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
})

vim.cmd("colorscheme rose-pine")
```

**Comment by mvllow** [comment]
This should be fixed in the canary branch, thank you for reporting.

You could also add this to your config if you'd rather not try canary:

```lua
require("rose-pine").setup({
  highlight_groups = {
    GitSignsAdd = { bg = "NONE" },
    GitSignsChange = { bg = "NONE" },
    GitSignsDelete = { bg = "NONE" },
  }
})
```
