### ISSUE TITLE
feature: Add highlight for WinSeparator

### ISSUE THREAD

**Issue by fingolfin19** [rose-pine/neovim#191]
### Is your feature request related to a problem? Please describe.

Nvim is deprecating VertSplit and moving to WinSeparator in 0.10. By default, WinSeparator links to normal which does not look great for most colorschemes.

### Describe the solution you'd like

add highlight for WinSeparator to rose-pine

### Describe alternatives you've considered

Manually changing color for WinSeparator

**Comment by mvllow** [comment]
Thanks for the info, this has been added to the canary branch. Canary will most likely be merged into main once Neovim 0.10 is stable :)
