### ISSUE TITLE
Too much italic

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [rose-pine/neovim#192]
![image](https://github.com/rose-pine/neovim/assets/74532770/d54bf687-e249-4f0c-bc8d-cccdb0336041)
Why everything is italic?
How to make it look like this?
![image](https://github.com/rose-pine/neovim/assets/74532770/03990858-600a-44e3-9f09-ca2c3ea14e0f)

**Comment by mvllow** [comment]
Looks like you figured it out but for others stumbling across this:

```lua
require("rose-pine").setup({
  disable_italicts = true
})
```

In our canary branch italics are used a little less often and can be disabled entirely via:

```lua
require("rose-pine").setup({
  styles = { italic = false }
})
```

**Comment by ildar-shaymukhametov** [comment]
Thanks!
By the way, how to use the canary branch?

**Comment by mvllow** [comment]
Depending on your package manager, you add `branch = "canary"`:

{
  "rose-pine/neovim",
  branch = "canary"
}
