### ISSUE TITLE
bug: treesitter highlight issue

### ISSUE THREAD

**Issue by rgruyters** [rose-pine/neovim#193]
### Neovim version (nvim -v)

NVIM v0.9.5

### Terminal

Wezterm

### Describe the bug

On Python files the type coloring is not changed when highlight is enabled for Treesitter

### Steps To Reproduce

1. Use the minimal config below
2. Open a test python script
3. defined variables have the same color as the type

```python
from dataclasses import dataclass

@dataclass
class Person:
    name: str
    age: int
    email: str
    id: int
```

### Expected Behavior

Expect type has a different color than a variable. (see screenshot with catppuccin)

<img width="387" alt="Screenshot 2024-01-05 at 17 09 49" src="https://github.com/rose-pine/neovim/assets/2082795/7475ba53-8daa-46bd-9a1f-625535c7bbc2">

### Repro

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  rose_pine = 'https://github.com/rose-pine/neovim',
  treesitter = 'https://github.com/nvim-treesitter/nvim-treesitter',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/' .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ 'git', 'clone', '--depth=1', url, install_path })
  end
end

require('rose-pine').setup({
  -- ADD ROSÉ PINE CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
})

require('nvim-treesitter.configs').setup({
  ensure_installed = {
    'lua',
    'vimdoc',
    'vim',
    'python',
  },
  auto_install = false,
  highlight = { enable = true },
})

vim.cmd('colorscheme rose-pine')
```

**Comment by mvllow** [comment]
Sorry, could you elaborate on what exactly you'd like the result to be? Are you saying `dataclasses` should be different from `name`, `age`, etc.?

<img width="311" alt="Screenshot 2024-01-05 alle 21 35 10" src="https://github.com/rose-pine/neovim/assets/1474821/f9095aba-c75a-461f-b1ff-d6abfad9de0b">

**Comment by rgruyters** [comment]
No, type `str` of `name` should be a different color as shown in your screenshot. I don't know why it doesn't show in my test. I have used the repro config, but it is not shown in my terminal.

<img width="347" alt="Screenshot 2024-01-06 at 12 25 20" src="https://github.com/rose-pine/neovim/assets/2082795/4105038d-2607-42d2-8fe7-a905bd61bdd5">

**Comment by mvllow** [comment]
Ah, those must be from the language server. If you can provide the output of `:Inspect` on both the variable and the type I can offer more assistance. I’m assuming those groups will start with “@lsp”

**Comment by rgruyters** [comment]
There is no `@lsp` when I view `:Inspect`.

variable:
```
Treesitter
  - @variable.python links to @variable python
  - @field.python links to @field python
```

type:
```
Treesitter
  - @variable.python links to @variable python
  - @type.python links to Type python
  - @type.builtin.python links to Type python
```

**Comment by mvllow** [comment]
Gotcha, thanks for those. This is the same for other languages as well, we set types and fields to foam. Although not ideal, I think for now it's best to modify your personal config:

```lua
require("rose-pine").setup({
  highlight_groups = {
    "@field.python" = "iris" -- this can be any named palette value
  }
})
```

It's hard to not have fields be the same colour as some value because the value can be a type (foam), number (rose), string (gold), variable (text), etc.

**Comment by rgruyters** [comment]
Thanks, unfortunately your solution didn't work. (gives Lua errors)

This one works

```lua
require("rose-pine").setup({
  highlight_groups = {
    Type = { fg = "iris" },
  },
})
```

**Comment by mvllow** [comment]
I updated my comment above, I was missing square brackets around the key. Glad you got it to work though :)

**Comment by rgruyters** [comment]
Thanks for the update and the great help. Eventually went for

```lua
require("rose-pine").setup({
      highlight_groups = {
        ["@field"] = { fg = 'text' },
        ["@attribute"] = { fg = 'subtle' },
      },
})
