### ISSUE TITLE
After update got an error

### ISSUE THREAD

**Issue by Kana-fi** [rose-pine/neovim#196]
What's wrong? Everything was working fine until the update.
![Screenshot 2024-01-07 at 10 57 16 PM](https://github.com/rose-pine/neovim/assets/106124331/8d9f2719-e7bd-41a4-aa7f-7a6b98ce83fa)
![Screenshot 2024-01-07 at 10 53 56 PM](https://github.com/rose-pine/neovim/assets/106124331/eb9bdd82-a574-415c-b8ee-e03381899745)

**Comment by mvllow** [comment]
The error states that inherit is not a valid key in your custom highlight groups. I will look into it but remove that in the meantime and it should work
