### ISSUE TITLE
Wallpapers used in the screenshots

### ISSUE THREAD

**Issue by migueravila** [rose-pine/neovim#2]
Hi! As the title says I'd love to have that wallpapers! :heart:

**Comment by mvllow** [comment]
Here ya go :) 

![86E1F978-CBC3-46B0-8CF7-98BB9EB137A9](https://user-images.githubusercontent.com/1474821/128650757-51e5206b-b4e3-42f9-8f7a-5a1486347c8d.JPG)

I originally got it from https://dynamicwallpaper.club but unfortunately I don't see it there anymore
