### ISSUE TITLE
bug: `styles.transparency` not working

### ISSUE THREAD

**Issue by loqusion** [rose-pine/neovim#203]
### Neovim version (nvim -v)

v0.10.0-dev-2042+g28c183b38c

### Terminal / multiplexer

foot

### Describe the bug

`styles.transparency` set to `true` should make the editor background transparent, but instead it is opaque. (`styles.italic` is set to `false` here as a control group, and it seems to be working as intended.)

![image](https://github.com/rose-pine/neovim/assets/38332081/ee0bb0ce-afad-431a-85e2-5beaa7f76665)

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({
  styles = { transparency = true }
})

vim.cmd("colorscheme rose-pine")
```

**Comment by mvllow** [comment]
This seems quite important to have for an update claiming to improve transparency! Thanks for the report, silly mistake on my end :)
