### ISSUE TITLE
bug: netrw directories do not have colours

### ISSUE THREAD

**Issue by mirandaio** [rose-pine/neovim#219]
### Neovim version (nvim -v)

0.9.2

### Terminal / multiplexer

iTerm2

### Describe the bug

rose-pine commit 2a4aad89a803c84d7d1555d136639cd48ade1d64 does not colour directories in netrw:

<img width="902" alt="Screenshot 2024-01-26 at 08 11 05" src="https://github.com/rose-pine/neovim/assets/1652699/4d396846-d3e4-4ac5-b293-33735654dd18">

while commit e29002cbee4854a9c8c4b148d8a52fae3176070f (the last one I had before I updated rose-pine) did:

<img width="887" alt="Screenshot 2024-01-25 at 23 11 56" src="https://github.com/rose-pine/neovim/assets/1652699/f83075ff-2a0e-4e5d-9935-daddc5c24a83">

Could we colour directories in netrw like it was before? It's easier to distinguish directories from files if they are coloured differently.

Thanks!

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({})

vim.cmd("colorscheme rose-pine")
```

**Comment by mvllow** [comment]
That's fair, the bold varies quite heavily depending on font/weights. It is coloured, however, if you set `styles.bold = false` but we probably should always colour them.

You could add this to your config until a change is pushed:

```lua
{
  highlight_groups = {
    Directory = {fg = "foam"}
  }
}
```
