### ISSUE TITLE
feature: Revert back color for `@variable.builtin` from "text" to "love", and add highlight for `@lsp.type.selfKeyword`

### ISSUE THREAD

**Issue by nicejji** [rose-pine/neovim#224]
### Describe the solution you'd like

After #217  `@variable.builtin` now looks the same as `@variable`, when lsp not provide`@lsp.type.selfKeyword` , treesitter defaults it to `@variable.builtin` which in turn now looks same as `@variable`, and it makes code hard to read.

**Comment by mvllow** [comment]
We can consider ways to differentiate when bold is not available but I'm not sure if "love" is the best option. We also need consistent ways to show builtin functions, methods, types, etc.

Happy to hear other's thoughts on this too... if we're okay having only builtin variables differentiated with "love" then that's fine and we can revert. I simply question if builtin variables are more important than builtin types, for example.

**Comment by nicejji** [comment]
> We can consider ways to differentiate when bold is not available but I'm not sure if "love" is the best option. We also need consistent ways to show builtin functions, methods, types, etc.
> 
> Happy to hear other's thoughts on this too... if we're okay having only builtin variables differentiated with "love" then that's fine and we can revert. I simply question if builtin variables are more important than builtin types, for example.

As for now, it is hard to distinguish expressions that include self/this in a code. Example in rust below.

<img width="692" alt="Screenshot 2024-01-28 at 02 04 34" src="https://github.com/rose-pine/neovim/assets/89997671/aa12ee69-c58c-4213-98e0-eab79a7b92fe">

**Comment by sjclayton** [comment]
Yeah I would also agree that reverting would probably be best for just builtin variables, as it is a lot easier to read with them differentiated and nicer looking as well.

**Comment by mvllow** [comment]
Fair enough, I’ll revert once I’m back at the computer. Appreciate the input :)

**Comment by mvllow** [comment]
Okay, #226 handles reverting the builtin variable highlight.

As far as `@lsp.type.selfKeyword`, could someone share a screenshot of what this looks like and the desired colour for it?

**Comment by nicejji** [comment]
> Okay, #226 handles reverting the builtin variable highlight.
> 
> As far as `@lsp.type.selfKeyword`, could someone share a screenshot of what this looks like and the desired colour for it?

I think there is no need to add separate color for `@lsp.type.selfKeyword`, cause it is look consistently in different languages.
<img width="1001" alt="image" src="https://github.com/rose-pine/neovim/assets/89997671/f4fa9477-8b43-441a-a42c-6d121a1be4e0">

<img width="1001" alt="image" src="https://github.com/rose-pine/neovim/assets/89997671/862fa48d-4aac-4348-a728-b0aa86620ab7">
