### ISSUE TITLE
bug:  consts not highlighted in Rust

### ISSUE THREAD

**Issue by 0xDmtri** [rose-pine/neovim#227]
### Neovim version (nvim -v)

0.9.5

### Terminal / multiplexer

wezterm

### Describe the bug

const I_AM_A_CONSTANT not highlighted properly anymore after the new tree sitter related commit.

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({})

vim.cmd("colorscheme rose-pine")
```

**Comment by nicejji** [comment]
It is caused by lsp semantic tokens overwriting treesitter highlights for `@constant`. And for now there is no additional highlights for lsp tokens such as `@lsp.typemod.variable.constant`
<img width="1001" alt="image" src="https://github.com/rose-pine/neovim/assets/89997671/60097ca4-6650-4645-9314-9c0910fe396f">
I think the best option for now is to do following, the way it done it catpuccin theme:
`["@lsp.type.variable"] = {}, -- use treesitter styles for regular variables`

**Comment by 0xDmtri** [comment]
> It is caused by lsp semantic tokens overwriting treesitter highlights for `@constant`. And for now there is no additional highlights for lsp tokens such as `@lsp.typemod.variable.constant` <img alt="image" width="1001" src="https://private-user-images.githubusercontent.com/89997671/300408405-60097ca4-6650-4645-9314-9c0910fe396f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjM0MDksIm5iZiI6MTcwNjUyMzEwOSwicGF0aCI6Ii84OTk5NzY3MS8zMDA0MDg0MDUtNjAwOTdjYTQtNjY1MC00NjQ1LTkzMTQtOWMwOTEwZmUzOTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDEwMTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMWMxYjFhNzc0YmIzNDkyZDU4YjgwMjU0MzQyNDlmMzBmOWQ5ZTM3NDQwMDkwNTQ4YTA4ZGJmNzkzN2Q2ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1bpMmBi0E_ScOHf9cSovDGWVYJAAkgzxsxc34noRBRw"> I think the best option for now is to do following, the way it done in catpuccin theme: `["@lsp.type.variable"] = {}, -- use treesitter styles for regular variables`

ah I see, thanks, that makes sense!
