### ISSUE TITLE
bug: Highlighting in markdown files not working as expected

### ISSUE THREAD

**Issue by techiemohitjangra** [rose-pine/neovim#228]
### Neovim version (nvim -v)

0.9.5

### Terminal / multiplexer

Kitty / Tmux

### Describe the bug

highlighting  for mark down file not working properly, was previously working on commit 67b0313 but after update none of the highlighting worked, I trued rolling back to this commit, it still didn't work. On the most recent update (commit b2c8def) highlighting partially works, all heading level are highlighted in the same color now. 

I haven't use neovim for long, rolling back might not have working because of my setup or something. Let me know  if i can do something to help you figure out the issue

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({
  -- ADD ROSÉ PINE CONFIG THAT IS _NECESSARY_ TO REPRODUCE THE ISSUE
  variant = 'main',
})

vim.cmd("colorscheme rose-pine")
```

**Comment by TinusgragLin** [comment]
Most likely due to the recent treesitter change: https://github.com/nvim-treesitter/nvim-treesitter/pull/5831
