### ISSUE TITLE
feature: add config option to disable syntax highlighting

### ISSUE THREAD

**Issue by hayook** [rose-pine/neovim#241]
### Describe the solution you'd like

I am currently using Neovim with nvim-treesitter for syntax highlighting. However, conflicts have arisen where Rose-Pine overrides some highlights provided by nvim-treesitter, leading to bad code highlighting. 
To address this issue, I suggest the addition of a new configuration option. This option would enable users to disable the built-in syntax highlighting, offering a solution for those relying on nvim-treesitter or other syntax highlighting plugins.

**Comment by mvllow** [comment]
Could you provide screenshots of what you mean by "bad code highlighting"? Rosé Pine should work with the default highlight groups as well as treesitter and semantic tokens. If you're requesting being able to disable one of the categories above then we could consider how'd that look. I need a little more information first to know exactly what you're asking.
