### ISSUE TITLE
bug: rust constants not highlighted

### ISSUE THREAD

**Issue by Tom-Hadean** [rose-pine/neovim#245]
### Neovim version (nvim -v)

0.10

### Terminal / multiplexer

win terminal

### Describe the bug

Rust constants are not highlighted. This was reported as #227, fixed in #233, reverted in #240.

Suggest alternate fix:

```
diff --git a/lua/rose-pine.lua b/lua/rose-pine.lua
index 40ba83e..9f118e9 100644
--- a/lua/rose-pine.lua
+++ b/lua/rose-pine.lua
@@ -416,6 +416,7 @@ local function set_highlights()
                ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
                ["@lsp.typemod.operator.injected"] = { link = "@operator" },
                ["@lsp.typemod.string.injected"] = { link = "@string" },
+               ["@lsp.typemod.variable.constant"] = { link = "@constant" },
                ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
                ["@lsp.typemod.variable.injected"] = { link = "@variable" },

``` 

### Repro

```Lua
see #227
```

**Comment by mvllow** [comment]
Appreciate the report, linking to constant makes sense (due to naming) but I'm actually surprised constant is gold. If we're okay with that colour for constants I can merge #246

**Comment by 0xDmtri** [comment]
> Appreciate the report, linking to constant makes sense (due to naming) but I'm actually surprised constant is gold. If we're okay with that colour for constants I can merge #246

Yes please!
