### ISSUE TITLE
feature: maybe set DiagnosticOk highlights

### ISSUE THREAD

**Issue by fredrikfoss** [rose-pine/neovim#255]
### Describe the solution you'd like

Hey, this is minor but I by chance saw that the DiagnosticOk highlight isn't set by the colorscheme. Right now it uses guifg=NvimLightGreen. I don't mind the color, but the DiagnosticVirtualTextOk highlight won't get a blended background like the other 4 ones :)

### Additional context

```
$ nvim -v
NVIM v0.10.0-dev+2663-gc1c6c1ee1
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Run "nvim -V1 -v" for more info
```

**Comment by mvllow** [comment]
Do you have a screenshot/example of when this highlight is used? Happy to add support here but not sure how to test

**Comment by sjclayton** [comment]
I also don't mind the color of `NvimLightGreen` and think it fits in with the rose-pine palette quite nicely.

[which-key.nvim](https://github.com/folke/which-key.nvim) is now using `DiagnosticOk` as it's base linking for green to display it's icons if you don't use icon colors inherited from [mini.icons](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-icons.md)

**Comment by fredrikfoss** [comment]
You can test by checking out the highlights section of the diagnostic help page:

```
:h diagnostic-highlights
:h hl-DiagnosticOk
:h hl-DiagnosticVirtualTextOk
```

**Comment by sjclayton** [comment]
@fredrikfoss 

We will have to wait for @mvllow to weigh in more on this... like I said I am fine with using the green color `NvimLightGreen` and could go a head and submit a PR to add highlights for both `DiagnosticOk` and `DiagnosticVirtualTextOk`. 

But I would like to see if there is anything @mvllow has to say about this first.

**Comment by mvllow** [comment]
Ideally we would use a colour from our existing palette _but_ we do have this super secret leaf green `#6d8f89` in some of our brand material. We've used it atop the main and dawn base backgrounds so hopefully that could look good between all variants. Haven't tested personally but if someone wants to share a screenshot of it in use that'd be much appreciated :)

**Comment by sjclayton** [comment]
@mvllow 

I am going to do some testing, and play around with that color a bit and see what it looks like applying it to various things in my config... and I will post the results here.

**Comment by sjclayton** [comment]
@mvllow 

From the little bit of early testing I've done so far.... the leaf green color looks OK.... it's still a bit dark for my liking, in order to have it look good across all variants I think the saturation should be increased about 10%... so it would end up as `#629a90`, without increasing the saturation `moon` is the only variant it looks too dark on...

**Comment by mvllow** [comment]
I found `#769B94` deep in the archives, which does seem close to your new colour and looks a bit better on moon than the original I sent over.

**Comment by sjclayton** [comment]
I just tried it out, it looks ok... I still think `#629a90` looks better and it is a direct relation of the original leaf green you sent just boosted a tiny bit, where as the new one is more lightened than boosted.

Here is a screenshot of all three side-by-side, let me know what you think.

![2024-07-20_17-13](https://github.com/user-attachments/assets/a2c738e5-57b8-4c13-898e-1bdff7b49965)

**Comment by mvllow** [comment]
I think I misspoke initially. From our branding material, `#6d8f89` is the leaf colour for dawn and `#769b94` is the leaf colour for main/moon. We can tweak them of course but they should be different per light/dark variants. I'm pretty happy with the dawn colour, but for main/moon we could lighten it to perhaps `#95b1ac`?

**Comment by sjclayton** [comment]
@mvllow 

I'm good with your current proposal. I was also wondering if this would mean this color set is added to the palette as a named color or no? If so I would just call it 'leaf' 😃

**Comment by mvllow** [comment]
If you want to add leaf to the palette file that’s fine with me. I don’t see it going much further than our Neovim theme for now but it doesn’t hurt :)

**Comment by sjclayton** [comment]
@mvllow 

I will be submitting additional PR's that rely on #290, to update some existing plugin support to include the new color.

Don't get me wrong, I love the palette, however I think there are situations where it can be hard to achieve proper styling with only 6 colors.... Neovim is one of those situations. I wasn't thinking you were going to necessarily add `leaf` to the main palette for everything. Thanks for your input with this!! 💯
