### ISSUE TITLE
bug: Semantic Highlight Token Issue with Python

### ISSUE THREAD

**Issue by akthe-at** [rose-pine/neovim#256]
### Neovim version (nvim -v)

Neovim Nightly

### Terminal / multiplexer

Wezterm

### Describe the bug

Basedpyright is a relatively new python LSP that is a fork of the popular and commonly used pyright lsp. However, pyright lsp does not have semantic tokens as a feature. Several color schemes have begun to make alterations to their codebase in the last day or so to accommodate this change because as of right now the tokens are breaking the highlights when enabled. See Photo. 

![image](https://github.com/rose-pine/neovim/assets/105152139/71694e81-ca87-4928-b3cc-862b4300af78)

Proposed fix requires ~ 2 lines of code change, and the first person I saw make this change was Folke with this [Tokyonight commit.](https://github.com/folke/tokyonight.nvim/commit/2983390e0ee59a40c02bb90df9bad860f251534a) A PR will be coming shortly from myself with one additional change to Folke's because of the difference in how lsp variable highlights are linked currently.

**Comment by IamGianluca** [comment]
I'm also seeing this issue. From what I can see, it mostly impacts the import statements.

With `basedpyright':
![image](https://github.com/rose-pine/neovim/assets/4025968/08770ac9-eb97-4430-9860-638922bb7367)

Without `basedpyright` (`:LspStop`):
![image](https://github.com/rose-pine/neovim/assets/4025968/430ef938-aaac-43e0-bab3-9df049ab6b33)
