### ISSUE TITLE
bug: weird highlight behavior (Rust)

### ISSUE THREAD

**Issue by 0xDmtri** [rose-pine/neovim#258]
### Neovim version (nvim -v)

NVIM v0.9.5

### Terminal / multiplexer

WezTerm

### Describe the bug

When at the last line of a method, the highlight behavior randomly changes (Rust).

Here are the examples:

<img width="426" alt="Screenshot 2024-03-24 at 14 54 57" src="https://github.com/rose-pine/neovim/assets/33504992/ca52faef-e86f-4ac9-9984-7255742b78fd">

<img width="437" alt="Screenshot 2024-03-24 at 14 58 34" src="https://github.com/rose-pine/neovim/assets/33504992/4d226c97-7957-4aff-baa5-074b3c798c0f">

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({
  -- ADD ROSÉ PINE CONFIG THAT IS _NECESSARY_ TO REPRODUCE THE ISSUE
})

vim.cmd("colorscheme rose-pine")
```

**Comment by mvllow** [comment]
Hmm, not able to reproduce this. What are the highlight groups you get when running `:Inspect` while hovering over both the iris `dbg` and rose `dbg`?

It looks like without treesitter, macros are iris. With treesitter, macros are rose. Finally, semantic tokens would end up making them gold. So honestly this might be a treesitter issue.

**Comment by 0xDmtri** [comment]
> Hmm, not able to reproduce this. What are the highlight groups you get when running `:Inspect` while hovering over both the iris `dbg` and rose `dbg`?
> 
> It looks like without treesitter, macros are iris. With treesitter, macros are rose. Finally, semantic tokens would end up making them gold. So honestly this might be a treesitter issue.

U are absolutely right, its a tree sitter issue. Thanks!
