### ISSUE TITLE
bug: neotree tabs not highlighted

### ISSUE THREAD

**Issue by mikemykhaylov** [rose-pine/neovim#263]
### Neovim version (nvim -v)

0.9.5

### Terminal / multiplexer

Wezterm

### Describe the bug

Inactive neo-tree tabs are not colored, using the default colors

<img width="330" alt="Screenshot 2024-04-04 at 12 22 50" src="https://github.com/rose-pine/neovim/assets/32168861/25fee35a-c673-422a-be65-287775cf8675">

**Comment by mvllow** [comment]
I would happily accept a PR for this—not sure the highlight groups they use but probably similar to nvim-tree

**Comment by mikemykhaylov** [comment]
Just checked, not fixed :( I might take a look over the weekend
