### ISSUE TITLE
bug: integrated terminal status line wrong color

### ISSUE THREAD

**Issue by morhaham2** [rose-pine/neovim#266]
### Neovim version (nvim -v)

0.9.5

### Terminal / multiplexer

wezterm

### Describe the bug

In Neovim, the integrated terminal status line is shown with the wrong color. It is not related to tmux because i've tried it outside a tmux session as well. I've also tried with iTerm2 and the same as in Wezterm.

<img width="961" alt="image" src="https://github.com/rose-pine/neovim/assets/156217168/2d7bd0fb-c672-472d-8692-a60cdcb75dea">

### Repro

```Lua
  {
    "rose-pine/neovim",
    name = "rose-pine",
    priority = 1000,
    lazy = false,
    config = function()
      vim.cmd("colorscheme rose-pine")
    end,
  },

```

**Comment by mvllow** [comment]
This is the expected colour for the terminal statusline though..

**Comment by morhaham2** [comment]
> This is the expected colour for the terminal statusline though..

Wow really.. very weird color .How can I change that?

**Comment by mvllow** [comment]
The entire terminal theming can be disabled via `options.enable.terminal = false`

https://github.com/rose-pine/neovim/blob/17b466e79479758b332a3cac12544a3ad2be6241/lua/rose-pine.lua#L885-L915

You should be able to override the two groups, though:

```lua
highlight_groups = {
  StatusLineTerm = { fg = "subtle", bg = "surface" },
  StatusLineTermNC = { fg = "muted", bg = "surface", blend = 60 }
}
```

If the above doesn't work let me know!

**Comment by morhaham2** [comment]
> The entire terminal theming can be disabled via `options.enable.terminal = false`
> 
> https://github.com/rose-pine/neovim/blob/17b466e79479758b332a3cac12544a3ad2be6241/lua/rose-pine.lua#L885-L915
> 
> You should be able to override the two groups, though:
> 
> ```lua
> highlight_groups = {
>   StatusLineTerm = { fg = "subtle", bg = "surface" },
>   StatusLineTermNC = { fg = "muted", bg = "surface", blend = 60 }
> }
> ```
> 
> If the above doesn't work let me know!

Thank you I'll check that soon.
Btw can you tell if you encountered color anomaly in text like this:
<img width="609" alt="image" src="https://github.com/rose-pine/neovim/assets/156217168/df90b0e0-d9e8-4250-bce9-0af4f6a16f99">

**Comment by mvllow** [comment]
That is usually an issue with treesitter

**Comment by morhaham** [comment]
> ```lua
>  StatusLineTerm = { fg = "subtle", bg = "surface" },
>   StatusLineTermNC = { fg = "muted", bg = "surface", blend = 60 }
> ```

I used the second solution it works, thank you.
