### ISSUE TITLE
bug: New lualine themes break "auto" lualine theme behaviour

### ISSUE THREAD

**Issue by Slotos** [rose-pine/neovim#268]
### Neovim version (nvim -v)

NVIM v0.10.0-dev-3045+gefaf37a2b

### Terminal / multiplexer

Kitty

### Describe the bug

Lualine's "auto" theme loads a theme that corresponds to `colorscheme` value, if present. New lualine themes make `rose-pine` lualine theme unaware of background color, effectively freezing it in its default dark variant.

The expectation is that lualine theme respects editor's `background` setting, and rose-pine's `dark_variant` setting, just as the main theme does.

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
  lualine = "https://github.com/nvim-lualine/lualine.nvim",
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("lualine").setup({})

vim.cmd("colorscheme rose-pine")
vim.cmd("set background light")
```

**Comment by mvllow** [comment]
Appreciate the report! Reverted the new themes for now.

**Comment by VoxelPrismatic** [comment]
I can still reproduce the issue. `set background` doesn't affect anything whatsoever.
