### ISSUE TITLE
bug: @float not capture group not highlighted by rose-pine

### ISSUE THREAD

**Issue by abvee** [rose-pine/neovim#272]
### Neovim version (nvim -v)

NVIM v0.10.0

### Terminal / multiplexer

tmux

### Describe the bug

Some of the queries for languages in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) name their float capture group `@float` instead of `@number.float`.

For example, the `go` queries use `@float`. Rose-pine doesn't highlight this group, so all floats in the `go` language when using treesitter for syntax highlighting are unhighlighted.

### Repro

```Lua
vim.cmd "colorscheme rose-pine-moon"
--enable treesitter. This section just starts treesitter
function checkSyntax()
	if not pcall(vim.treesitter.start) then
		print("Tree Sitter not enabled")
		vim.cmd('syntax on')
	end
end

local syntax = vim.api.nvim_create_augroup("SyntaxChecking", { clear = true })
vim.api.nvim_create_autocmd({"Filetype"}, {
	pattern = "*",
	group = syntax,
	callback = checkSyntax
})
```

**Comment by mvllow** [comment]
Closed by #273, thanks again :)
