### ISSUE TITLE
feature: Rust proc macro color

### ISSUE THREAD

**Issue by 0xDmtri** [rose-pine/neovim#275]
### Describe the solution you'd like

Could we please have a different color for Rust's proc macos? Currently they are highlighted as consts or statics which does not look ideal imho. I remember we used to have it as purplish...

**Comment by mvllow** [comment]
Happy to accept a PR that adds any language-specific highlights. I don't know enough Rust to be useful here. It should be pretty simple to add to your config as well and if you share that I can implement it into the theme if that's easier:

```lua
require('rose-pine').setup({
  highlight_groups = {
    -- Replace 'SomeGroup' with results from `:Inspect`
    SomeGroup = { fg = 'iris' }
  }
})
```

**Comment by 0xDmtri** [comment]
> Happy to accept a PR that adds any language-specific highlights. I don't know enough Rust to be useful here. It should be pretty simple to add to your config as well and if you share that I can implement it into the theme if that's easier:
> 
> 
> 
> ```lua
> 
> require('rose-pine').setup({
> 
>   highlight_groups = {
> 
>     -- Replace 'SomeGroup' with results from `:Inspect`
> 
>     SomeGroup = { fg = 'iris' }
> 
>   }
> 
> })
> 
> ```

Will look at it and draft PR shortly, thanks!

**Comment by 0xDmtri** [comment]
Actually current one is better, i was just used to an old one, lets keep it how it is, sorry for the mess :)
