### ISSUE TITLE
feature: Palette overrides

### ISSUE THREAD

**Issue by arkrost** [rose-pine/neovim#276]
### Describe the solution you'd like

Please add an option to override palette colours. Right now, I usually use `before_highlight` to make my adjustments:

```
require('rose-pine').setup({
before_highlight = function(group, highlight, palette)
   if highlight.fg == palette.pine then
     highlight.fg = "#XXXXXX"
   end
   ...
end
})
```

However, I'd prefer to have it as a standard option and have ability to add variants for all theme variants.

**Comment by mvllow** [comment]
Thank you for showing interest in this feature. It's on my radar :)

**Comment by mvllow** [comment]
Completed in #307 :)
