### ISSUE TITLE
bug: Confusing colors

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [rose-pine/neovim#278]
### Neovim version (nvim -v)

0.10.0

### Terminal / multiplexer

Standard Fedora 40 terminal

### Describe the bug

![image](https://github.com/rose-pine/neovim/assets/74532770/391dd382-9749-4be3-8c8c-b79509721381)

When cursor moves to area selected by search, colors become so confusing I do not understand where my cursor is
I think all selected chars should be yellow, but the char with the cursor should be more yellow?

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({
  -- ADD ROSÉ PINE CONFIG THAT IS _NECESSARY_ TO REPRODUCE THE ISSUE
})

vim.cmd("colorscheme rose-pine")
```

**Comment by mvllow** [comment]
It looks like your cursor is on "b", and unfortunately we can't change your cursor colour in Neovim. Your terminal emulator controls that (with some exceptions).

**Comment by ildar-shaymukhametov** [comment]
Ok, thanks
