### ISSUE TITLE
Support nvim-cmp

### ISSUE THREAD

**Issue by babygau** [rose-pine/neovim#28]
Hi, 

A recent merge of `nvim-cmp` make use of new floating windows. It would be great to have the theme support it. I'm aware that I could do it my own but it will not be in sync with your mind.

The following is its highlight group:

```
CmpItemAbbr
CmpItemMenu
CmpItemKind
CmpItemAbbr
CmpItemAbbrDeprecated 
CmpItemAbbrMatch
CmpItemAbbrMatchFuzzy 
```

Link for reference: https://github.com/hrsh7th/nvim-cmp#highlights

Thank you.

**Comment by babygau** [comment]
@mvllow many thanks for your response, it's working OK for me 👍. `CmpItemMenu` background color is actually of `PMenu`. That's why you don't see the difference :)

**Comment by danymat** [comment]
#37
