### ISSUE TITLE
bug: incorrect separator color for lualine buffer 

### ISSUE THREAD

**Issue by kdheepak** [rose-pine/neovim#288]
### Neovim version (nvim -v)

NVIM v0.11.0-dev-315+g46187117c Build type: RelWithDebInfo LuaJIT 2.1.1716656478 Run "nvim -V1 -v" for more info

### Terminal / multiplexer

alacritty / zellij

### Describe the bug

<img width="541" alt="image" src="https://github.com/user-attachments/assets/72bce6ef-cb2a-4294-97f6-663ee2907d98">

From `repro.lua` (`test.lua`):

```shell
$ nvim -u test.lua test.lua README.md aliases -c ":bnext"
```

<img width="758" alt="image" src="https://github.com/user-attachments/assets/a8777f7e-2a34-427a-9ab0-d3c7a4dcafe6">

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
  lualine = "https://github.com/nvim-lualine/lualine.nvim",
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({
  styles = {
    bold = true,
    italic = false,
    transparency = true,
  },
  highlight_groups = {
    Comment = { italic = true },
  },
})

require("lualine").setup({
  options = {
    icons_enabled = true,
  },
  sections = {
    lualine_a = { "mode" },
    lualine_b = { "branch", "diff", "diagnostics" },
    lualine_c = { { "filename", path = 1 } },
    lualine_x = { "encoding", "fileformat", "filetype" },
    lualine_y = { "progress" },
    lualine_z = { "location" },
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = { { "filename", path = 1 } },
    lualine_x = { "location" },
    lualine_y = {},
    lualine_z = {},
  },
  tabline = {
    lualine_a = { { "buffers", show_filename_only = false } },
    lualine_x = {},
    lualine_y = {},
    lualine_z = { "tabs" },
  },
  extensions = {},
})

vim.cmd("colorscheme rose-pine")
```

**Comment by sjclayton** [comment]
@kdheepak 

Couple quick questions... 

1) Have you tried another colorscheme such as say Catppuccin? If so, does it also exhibit the same behavior in the tabline in lualine? ie. the tab that is inactive is getting that white separator character? 

2) Does this only happen if you are on say the middle buffer out of 3, or like 2 out of 5? or does it happen on every single buffer no matter which is selected?

Because there is nothing in the way rose-pine configures the highlights for lualine that I can immediately see that would cause this to happen.

If you can provide a bit more information, it would greatly help in triaging this issue. Thanks! 😄

**Comment by kdheepak** [comment]
The issue doesn't occur with other colorschemes:

<img width="290" alt="image" src="https://github.com/user-attachments/assets/9ec216fd-eb7f-4c35-a5ac-e366fd6e72cf">

I narrowed the issue down to transparency:


```lua
require("rose-pine").setup({
  styles = {
    transparency = false, -- no issue
    -- transparency = true, -- issue occurs
  },
})
```

<img width="289" alt="image" src="https://github.com/user-attachments/assets/519653ab-0aa8-4dc2-9245-4219d903d163">

I'm not sure if that's an issue with lualine or this repo.

**Comment by mvllow** [comment]
I think #301 should fix this

**Comment by kdheepak** [comment]
I tested it out and it fixes it for me! Thanks for the responsive changes!

**Comment by kdheepak** [comment]
fwiw, I'm experiencing this exact issue again:

With `transparency=true`:

<img width="592" height="355" alt="Image" src="https://github.com/user-attachments/assets/828c74ef-5d23-47d7-b4eb-0d8d16c4de60" />

Without transparency set:

<img width="592" height="336" alt="Image" src="https://github.com/user-attachments/assets/4c92aea2-fc46-4d75-adb0-accc4bc4a873" />

**Comment by mvllow** [comment]
I’ve tried debugging this for a bit now with no luck. Removing the background of “NONE” works but then you don’t get a transparent background

**Comment by kdheepak** [comment]
It's also possible it is an upstream bug? May be worth reporting to neovim itself if a smaller reproducible version can be made.
