### ISSUE TITLE
bug: Diff doesn't show the difference within the line

### ISSUE THREAD

**Issue by leosmaia21** [rose-pine/neovim#289]
### Neovim version (nvim -v)

0.10

### Terminal / multiplexer

tmux

### Describe the bug

The diff between two file appears this way:
![image](https://github.com/user-attachments/assets/2532b217-c6bd-4941-af3c-ce6431918945)
however it should appear like this, (in this image i am using the default theme from neovim):
![image](https://github.com/user-attachments/assets/ce6ab0c0-5bb9-4de3-9ddf-2f15853c82ea)
Thank you

**Comment by mvllow** [comment]
Is this no longer an issue? Happy to look into this further but will need some steps to reproduce as I'm not too familiar with the Neovim diff feature.

**Comment by leosmaia21** [comment]
Hi, I have looked into the color scheme code, and i noticed that Diffchange(line that have differences) and Difftext(differences within the line) have the same color, I believe is the same in git diff that you have on readme.
If you want you can change for this ones:
 DiffAdd        ctermfg=0 ctermbg=10 guifg=NvimLightGrey1 guibg=NvimDarkGreen
DiffChange     guifg=NvimLightGrey1 guibg=NvimDarkGrey4
 DiffDelete     cterm=bold ctermfg=9 gui=bold guifg=NvimLightRed
 DiffText       ctermfg=0 ctermbg=14 guifg=NvimLightGrey1 guibg=NvimDarkCyan,

I believe people that are using diff, just want to see the differences clearly xD. 

Or if you want i can do a push request

**Comment by mvllow** [comment]
#297 should fix this, but I'll leave it open for a little in case you or anyone else has feedback. There's probably more improvements we could do regarding diff.
