### ISSUE TITLE
feature: Nvim treesitter context transparency to be handled automatically while the autocomplete menu preserves its non transparent state.

### ISSUE THREAD

**Issue by bhuvneshuchiha** [rose-pine/neovim#296]
### Describe the solution you'd like

I want that there should be an option to set the nvim treesitter context transparecy to true, but the bg color of the auto completion menu should be there. Other themes such as toyonight storm and gruvbox give this option where if you set vim's float transparency vim.api.nvim_set_hl(0, "Float", { bg = "none" })
by doing this, the treesitter becomes transparent but we can have the autocompletion bg color which looks good on the theme.
<img width="1512" alt="Screenshot 2024-07-22 at 5 07 52 PM" src="https://github.com/user-attachments/assets/01712a17-3572-49ad-bc9f-6483174cf8e1">

### Additional context

I want the treesitter-context transparency setting handled automatically... like it is now, after @sjclayton latest fix. But I want the auto complete popup to keep it's non-transparent state even when transparency is enabled.

**Comment by bhuvneshuchiha** [comment]
@sjclayton here FYI

**Comment by sjclayton** [comment]
If this feature is to be added at some point, it should definitely be only as an option, as there are for sure plenty of people who like the existing behavior.

**Comment by bhuvneshuchiha** [comment]
Totally fine. Getting an option to implement this setting will be the best. As trust me there are lot of people who will like this feature as well that we are discussing here. And rose pine will be the first theme to bring these both features together. the existing one and this one.

**Comment by bhuvneshuchiha** [comment]
Just curious, will this be done soon? XD

**Comment by sjclayton** [comment]
I can't say for sure, we will have to wait for more input from others and the maintainer as well...

**Comment by bhuvneshuchiha** [comment]
Sure, understandable.. Thanks for considering the request!

**Comment by mvllow** [comment]
Wouldn't this be as simple as updating `Pmenu` in `highlight_groups` as the user? If it is a single highlight group that needs updated then we can add a recipe in the wiki. Less options is ideal :)

**Comment by sjclayton** [comment]
@mvllow 

I am far in favour of something along those lines instead of adding another option as well myself. Will do some experimenting to see if just `Pmenu` covers things... as potentially there maybe situations where more hl groups are used.

**Comment by bhuvneshuchiha** [comment]
but updating the Pmenu will give the same color to all the themes regardless if the theme is rose pine or some other. it would be great if this can be done just for rose pine and when the user changes the theme, they get the bg color of autocomplete of that particular theme ... Just a thought

**Comment by sjclayton** [comment]
@bhuvneshuchiha 

That is not normal behavior, the highlight groups are cleared and reset when you switch themes (if the theme creator did things correctly, which most should, certainly all the popular ones do). So if we changed `Pmenu` in rose-pine then that change would only affect rose-pine.

**Comment by bhuvneshuchiha** [comment]
<img width="1512" alt="Screenshot 2024-07-23 at 1 30 00 AM" src="https://github.com/user-attachments/assets/158739ba-824f-4e55-adf1-339d44965c86">


Did I do it correctly? Previously I was adding the Pmenu highlight mods in my init file thats why they were being applied to every theme.. Now i have added them in rose pine's config only.

Works like a charm! 

Thanks @sjclayton @mvllow

**Comment by sjclayton** [comment]
@bhuvneshuchiha 

Yeah that looks right... although your screenshot doesn't look transparent at all, the background is black. You can also specify named palette colors instead of the hex values, so your config would look like:

```lua
highlight_groups = {
  Pmenu = { fg = 'subtle', bg = 'surface' },
  PmenuSel = { fg = 'text', bg = 'overlay' },
}
```

As well the highlight overrides you have for treesitter-context are not needed anymore after my fix, so you could remove them.

**Comment by bhuvneshuchiha** [comment]
![Uploading Screenshot 2024-07-23 at 2.06.20 AM.png…]()


Its transparent now !!

**Comment by bhuvneshuchiha** [comment]
<img width="1512" alt="Screenshot 2024-07-23 at 2 06 20 AM" src="https://github.com/user-attachments/assets/27fcf043-4cbf-4719-a0be-41837e7897ee">

Its transparent now !!!

**Comment by sjclayton** [comment]
If everything is all good then, this issue can be closed.
