### ISSUE TITLE
bug: when turning on the transparency, the status line also becomes transparent, making it hard to see.

### ISSUE THREAD

**Issue by bhuvneshuchiha** [rose-pine/neovim#302]
### Neovim version (nvim -v)

v0.10.0

### Terminal / multiplexer

tmux

### Describe the bug

when turning on the transparency, the status line also becomes transparent, making it hard to see.
<img width="1512" alt="Screenshot 2024-07-24 at 10 06 01 AM" src="https://github.com/user-attachments/assets/8a04d832-458d-4491-8aaa-4b5745d03e02">

### Repro

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
  rose_pine = "https://github.com/rose-pine/neovim",
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = "/tmp/nvim/site/pack/test/start/" .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
  end
end

require("rose-pine").setup({
  -- ADD ROSÉ PINE CONFIG THAT IS _NECESSARY_ TO REPRODUCE THE ISSUE
})

vim.cmd("colorscheme rose-pine")
```

**Comment by bhuvneshuchiha** [comment]
but if I do disable background = true,

then the background becomes transparent, and the status line reappears. But again, disable background doesnt work with nvim treesitter context.

<img width="1512" alt="Screenshot 2024-07-24 at 10 10 29 AM" src="https://github.com/user-attachments/assets/b2492832-670a-4516-a73c-ab91a39b6668">

**Comment by bhuvneshuchiha** [comment]
@sjclayton do you mind checking this one sir?

**Comment by bhuvneshuchiha** [comment]
This grey background of the theme is basically Alacritty theme, so transparency and disable background both are working to disable rose pine's background color.

**Comment by bhuvneshuchiha** [comment]
StatusLine= { fg = "subtle", bg = "surface" }

I have managed to get this working using the above highlight group. Is there any other fix or should I keep the above setting?

**Comment by sjclayton** [comment]
@bhuvneshuchiha 

Nothing has changed in regards to treesitter-context... and the status line shouldn't ever be transparent, so setting `transparency = true` which is the correct setting, there is no setting called `disable_background` anymore - should result in treesitter-context being transparent and the status line being fully opaque. 

The transparency for tree-sitter context is still fully working for me with the current state of the plugin (latest commit) on both nvim 0.10.0 and nightly. 

Please check to ensure you are using the correct options and there are no other highlight overrides or any other config that could be causing this on your end.

**Comment by sjclayton** [comment]
@bhuvneshuchiha 

Please remove the lines in your rose-pine config highlight group overrides for treesitter-context as the fix is integrated into rose-pine as of a few days ago, they're no longer needed for your situation.

That will resolve this.

**Comment by bhuvneshuchiha** [comment]
<img width="1512" alt="Screenshot 2024-07-24 at 12 51 51 PM" src="https://github.com/user-attachments/assets/4d3f9e25-2a98-4b5a-b331-921feb8b2ebf">


Here as you can see, my status line is also transparent.

**Comment by bhuvneshuchiha** [comment]
<img width="1512" alt="Screenshot 2024-07-24 at 12 58 46 PM" src="https://github.com/user-attachments/assets/5b661f7a-787f-4198-a93c-7aa88687a256">


For tokyonight, the status line is perfectly non-transparent while the theme is transparent.. I have checked no setting is overriding the status line color as well. The issue is with rose-pine i suppose. For every other theme its working cool

**Comment by sjclayton** [comment]
There is no issue on my end, that's the thing... the theme (rose-pine) is behaving as it should. 

So there must be something you are doing in your terminal (Alacritty?) config, that is causing yours to look different. Other themes have different ways of handling transparency and they may not be affected by whatever setting is causing rose-pine to bug out in your case.

**Comment by sjclayton** [comment]
Sorry I just noticed your using the default status line.

But shouldn't be affected by these changes for lualine anyways --> #301 

and the transparency code for the normal default status line, hasn't changed recently.... and currently sets this when `transparency = true`

```lua
StatusLine = { fg = palette.subtle, bg = "NONE" },
StatusLineNC = { fg = palette.muted, bg = "NONE" },
```

**Comment by sjclayton** [comment]
![2024-07-24_04-30](https://github.com/user-attachments/assets/353b2b53-e3b5-48a0-83cb-5983509889c3)

**Comment by bhuvneshuchiha** [comment]
Got it @sjclayton . Just a last request as I know I am bugging you since couple of days XD . Can you share me the config for your lualine?? that looks so dope man!!!

**Comment by sjclayton** [comment]
@bhuvneshuchiha

Don't worry about it, happy to help.

That isn't lualine -- that is my tmux status line... and is highly customized and may not work well outside of my system... also it doesn't use rose-pine (it uses Catppuccin, as that is my main system wide theme for everything, except Neovim 😉)

This issue should be closed then, if all is good now...

**Comment by sjclayton** [comment]
@bhuvneshuchiha 

You're welcome!!

Go ahead and close it then 😛

**Comment by bhuvneshuchiha** [comment]
Hahah done!
