### ISSUE TITLE
rfc: new `Search` highlight

### ISSUE THREAD

**Issue by mvllow** [rose-pine/neovim#305]
#304 changed `Search` to be "rose". This is a discussion for making it neutral and not stand out as much as "text".

**Comment by mvllow** [comment]
require("rose-pine").setup({
	highlight_groups = {
		Search = { bg = "muted", blend = 20, inherit = false },
	},
})

<img width="139" alt="Screenshot 2024-07-25 alle 16 56 59" src="https://github.com/user-attachments/assets/5bd5a27e-20bc-47a9-af58-27e2b436465e">

**Comment by sjclayton** [comment]
That works fine for `dawn` but on `moon` and `main` its not very visible. I went with rose because I tried various combos of other colors with various blends and nothing seem to work as well on both `dawn` and the dark variants.

**Comment by mvllow** [comment]
It is tough to balance–this is why we ended up changing the bg to "text". I agree it can be sharp, but I guess I'm not usually leaving search visible for long

**Comment by mvllow** [comment]
```lua
require("rose-pine").setup({
	highlight_groups = {
		CurSearch = { fg = "base", bg = "rose", inherit = false },
		Search = { bg = "rose", blend = 20, inherit = false },
	},
})
```

<img width="134" alt="Screenshot 2024-07-25 alle 17 09 10" src="https://github.com/user-attachments/assets/6aaffe5e-bfe0-4c9b-876c-72bed039d4bb">

Sort of interesting using a solid for the current search and blended for others

**Comment by sjclayton** [comment]
That looks really good actually... 😲

**Comment by mvllow** [comment]
Only concern would be if we want to change the foreground for `Search`. I think for `CurSearch` it's fine—when on the current search you're pretty aware of your context but leaving the foreground alone for other searches could be useful to maintain context but also leads to some harder to read text:

<img width="312" alt="Screenshot 2024-07-25 alle 17 13 53" src="https://github.com/user-attachments/assets/41af93cd-4e23-4035-93bf-e7dbd54482ba">

**Comment by sjclayton** [comment]
I don't know that leaving the foreground alone is that necessary for maintaining context, I think it looks fine with it changed.

**Comment by mvllow** [comment]
```lua
require("rose-pine").setup({
	highlight_groups = {
		CurSearch = { fg = "base", bg = "rose", inherit = false },
		Search = { fg = "rose", bg = "rose", blend = 20, inherit = false },
	},
})
```

I love pine on dawn, but unfortunately not that readable on dark variants. Rose is probably the most versatile between variants.

**Comment by mvllow** [comment]
<img width="329" alt="Screenshot 2024-07-25 alle 17 26 33" src="https://github.com/user-attachments/assets/ce3a9677-653e-4ff2-af64-9dd4f097ec9c">
<img width="312" alt="Screenshot 2024-07-25 alle 17 26 52" src="https://github.com/user-attachments/assets/4b6cb127-90c8-49e1-a92d-f204df26badb">

**Comment by sjclayton** [comment]
HOLY SHIT!! 😮

**Comment by sjclayton** [comment]
I just tried

```lua 
          CurSearch = { fg = 'base', bg = 'leaf', inherit = false },
          Search = { fg = 'leaf', bg = 'leaf', blend = 20, inherit = false },
```
on `moon` which is my main variant, and the only thing is maybe we could increase the blend by 10?? it seems just a touch to dark at 20.

**Comment by mvllow** [comment]
This is a blend of 30, the text is slightly hard to read. A blend of 20 does give us WCAG AA contrast for moon.

As far as dawn, that's not a passing contrast. Changing leaf to `#516767` does get us there but it changes leaf quite a bit.

Might need to noodle this—I would say the blend of 20 would be fine to merge now to me, and I'm happy to revisit leaf as a whole to make it more accessible. Open to further discussion though

**Comment by sjclayton** [comment]
Alrighty - 20 blend is good, since it is better for contrast. Was 20 the blend you used in the original screenshot using leaf?

**Comment by mvllow** [comment]
### Text

<img width="67" alt="Screenshot 2024-07-25 alle 20 58 26" src="https://github.com/user-attachments/assets/db4e46f4-7ce2-4847-adfe-a413ce3843b3">
<img width="65" alt="Screenshot 2024-07-25 alle 20 58 12" src="https://github.com/user-attachments/assets/77bc0c7f-c3ce-41c4-812a-32550655f2aa">

### Leaf

<img width="69" alt="Screenshot 2024-07-25 alle 20 57 53" src="https://github.com/user-attachments/assets/72667967-1ad3-4e16-9072-015d92fc780f">
<img width="68" alt="Screenshot 2024-07-25 alle 20 57 28" src="https://github.com/user-attachments/assets/95d850b5-ab32-4e66-b6f2-770d86b62a12">


I think I narrowed it down to these two options for accessibility. The "text" variant is the best contrast and most neutral (of course). The "leaf" variant is a little more fun but honestly I'm leaning towards the neutral for the theme and the user is more than welcome to update it in their config. We could add all of these as recipes in the wiki.

**Comment by sjclayton** [comment]
I'd be ok with the neutral variant as in this form it is way less obtrusive than the original implementation. 👍🏻

**Comment by sjclayton** [comment]
What are the settings you used for leaf in the last screenshot?

**Comment by mvllow** [comment]
Ugh

<img width="289" alt="Screenshot 2024-07-25 alle 21 03 54" src="https://github.com/user-attachments/assets/6fb96941-b7ba-4470-81fd-6c94a44916a9">

**Comment by sjclayton** [comment]
What did it break?

**Comment by mvllow** [comment]
Just realised my cursor (for Ghostty at least) is invisible on the current search

**Comment by sjclayton** [comment]
Using which settings did that happen?

**Comment by mvllow** [comment]
```lua
CurSearch = { fg = "base", bg = "text", inherit = false },
Search = { fg = "text", bg = "text", blend = 20, inherit = false },

CurSearch = { fg = "base", bg = "leaf", inherit = false },
Search = { fg = "text", bg = "leaf", blend = 20, inherit = false },
```

**Comment by sjclayton** [comment]
Which was causing the cursor to be invisible for you in your terminal?

**Comment by sjclayton** [comment]
I am going to spend some time with the neutral implementation and see how it looks and feels during use.

**Comment by mvllow** [comment]
Changed the default to be neutral and added the [leafy](https://github.com/rose-pine/neovim/wiki/Recipes#leafy-search) example to the wiki recipes :)

**Comment by mvllow** [comment]
Well shoot, I completely forgot this messes with the cursor colour on some terminals. Using text should probably be avoided :/

I am using the leaf version personally, so may end up pushing that.
