### ISSUE TITLE
bug: Telescope Transparency Issue

### ISSUE THREAD

**Issue by dunnwithpuns** [rose-pine/neovim#312]
### Neovim version (nvim -v)

0.11.0

### Terminal / multiplexer

WSL 2.0 Ubuntu

### Describe the bug

Hey I'm new to neovim, so I'm not sure if it's a color-scheme issue or a skill issue. I'm using a mixture of theprimeagen's config and kickstart.nvim for context.  

I'm having some trouble getting the transparency setting to work with telescope. It works great on my regular setup and netrw, but whenever I open telescope, it changes to the regular dark background.

Any advice or suggestions is much appreciated, thanks!

![rose-pine-transparency-0](https://github.com/user-attachments/assets/89ac072b-19f4-45b3-9ea4-15edfff3d5c8)
![rose-pine-transparency-1](https://github.com/user-attachments/assets/488484f5-55d5-4b0b-abb3-d0331f4231d6)
![rose-pine-transparency-2](https://github.com/user-attachments/assets/026d3774-ecc0-4ae8-97f1-56651216f080)

### Repro

```Lua
function ColorMyPencils(color)
	color = color or "rose-pine"
	vim.cmd.colorscheme(color)

	vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
	vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })

	vim.api.nvim_create_autocmd("TextYankPost", {
		desc = "Highlight when yanking (copying) text",
		group = vim.api.nvim_create_augroup("kickstart-highlight-yank", { clear = true }),
		callback = function()
			vim.highlight.on_yank()
		end,
	})
end

return {
	{
		"rose-pine/neovim",
		name = "rose-pine",
		config = function()
			require("rose-pine").setup({

				enable = {
					terminal = true,
				},
				styles = {
					italic = true,
					bold = true,
					transparancey = true,
				},
				highlight_groups = {
					TelescopeBackground = { bg = "none" },
					TelescopeBorder = { fg = "highlight_high", bg = "none" },
					TelescopeNormal = { bg = "none" },
					TelescopePromptNormal = { bg = "none" },
					TelescopeResultsNormal = { fg = "subtle", bg = "none" },
					TelescopeSelection = { fg = "text", bg = "none" },
					TelescopeSelectionCaret = { fg = "rose", bg = "rose" },
					CurSearch = { fg = "base", bg = "rose", inherit = false },
					Search = { bg = "rose", blend = 20, inherit = false },
				},
			})
		end,
	},
}
```

**Comment by mvllow** [comment]
Hmm can't reproduce this on my system but you shouldn't need the `ColorMyPencils` or any other setting of backgrounds to "none"—looks like you have a typo though as it should be "transparency".

**Comment by dunnwithpuns** [comment]
Welp that will definitely do it haha thanks for the help and the lovely theme!

**Comment by dunnwithpuns** [comment]
Okay wait, second question, I've figured out that if I add `vim.opt.cursorline = false` to ColorMyPencils() and call it form within netrw, I can remove the cursor background line, but everytime I reopen netrw it comes back. Do you know of a way to edit that setting permanently?

**Comment by mvllow** [comment]
Pretty sure there's an autocmd event that is for the filetype of netrw or similar which you could then set `vim.opt.cursorline = false` if you want to only disable the cursorline while in netrw. Otherwise simply move that setting out of the function and it will apply always.

**Comment by dunnwithpuns** [comment]
Okay cool I have a current fix of just setting it by using `BufWinEnter` as the event and it seems to be working fine! Thanks for the help again!

**Comment by dunnwithpuns** [comment]
Sorry, I'm just all over the place lol. I couldn't find the netrw specific event, but I tried using the `BufWinEnter` event and it worked, but only when opening vim for the first time. For more context, I have `vim.opt.cursorline = false` already set in my options file, so there isn't a cursor line in whenever I'm in a file, but for whatever reason it's there for netrw, so I'm just kinda lost as to how that even happens lol.

**Comment by mvllow** [comment]
You might have a plugin that is enabling the cursorline. Either way not an issue with this theme so we can keep this closed.
