### ISSUE TITLE
feature: Add support for epwalsh/obsidian.nvim

### ISSUE THREAD

**Issue by anupam-basu** [rose-pine/neovim#322]
### Describe the solution you'd like

In the Dawn theme reading bullet points, checkboxes and links/reference texts  are but too light on my eyes. Here are some screenshots
<img width="260" alt="Screenshot 2024-10-20 at 9 23 08 AM" src="https://github.com/user-attachments/assets/4bda114f-6cc4-4707-a05a-330c8b9f72ae">
<img width="130" alt="Screenshot 2024-10-20 at 9 23 18 AM" src="https://github.com/user-attachments/assets/74b85fc0-77ca-453d-8c33-9979c395db56">
<img width="337" alt="Screenshot 2024-10-20 at 9 24 06 AM" src="https://github.com/user-attachments/assets/6ea9e10f-d475-4743-9c34-297b92ea411d">

Hoping for some more stark highlights than the current one. 

### Additional context

I've been using epwalsh/obsidian.nvim
and modified the setup to have more agreeable colors to my eyes, but I was hoping the default can be changed or updated. 

```
    require("obsidian").setup({
      ui = {
        hl_groups = {
          ObsidianBullet = { fg = "#b4637a" },
          ObsidianRefText = { underline = true, fg = "#286983" },
        },
      },...

```

These colors I thought were better, if there are any other suggestions for them, more than happy to accept !

**Comment by mvllow** [comment]
Ah those aren't Rosé Pine colours so we need to add support for that plugin. If you want to submit a PR with your preferred changes (ideally we would theme all colours for that plugin) that would be appreciated :) For simplicity we could match the checkbox unchecked to our gold, checked to our foam and their purple in the "Done List" example to be our iris.

A good way to test this locally would be:

```lua
require("rose-pine").setup({
  -- Accepts highlight names from rosepinetheme.com/palette
  highlight_groups = {
    ObsidianBullet = { fg = "muted" },
    ObsidianRefText = { fg = "iris", underline = true },
  }
})
```
