### ISSUE TITLE
feature: ability to override blend

### ISSUE THREAD

**Issue by williamhCode** [rose-pine/neovim#324]
### Describe the solution you'd like

I'm trying to set `WinBarNC = { fg = "subtle", bg = "NONE" }` using `highlight_groups`. However, there's no way to disable the blend. 

If I set blend to `nil`, it uses the plugin's `blend = 60`. If I do `blend = 0` however, bg gets set to `palette.base`.

Right now I can only disable blend by using `vim.api.nvim_set_hl` and overriding the highlight. 

I'm wondering if you guys could add a way to disable blend through `highlight_groups`.

**Comment by mvllow** [comment]
I think you need to add `inherit = false` to your highlight group, e.g. `WinBarNC = { fg = "subtle", bg = "NONE", inherit = false }`

Hope that helps!

**Comment by williamhCode** [comment]
That worked, thanks so much!
