### ISSUE TITLE
Better highlights for rose-pine

### ISSUE THREAD

**Issue by danymat** [rose-pine/neovim#36]
Hello !

I stumbled across [this](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-dark-theme-colors-to-the-menu), and I thought it would be cool to have a better appearance of rose-pine, for each type of CmpKind.

What do you think ?

**Comment by mvllow** [comment]
Love it! I don't use CmpKind but would definitely accept a PR for that addition

**Comment by danymat** [comment]
Nice, I will try to come out with a small PR for it 
Do you have any colors recommendations ?

**Comment by mvllow** [comment]
Seeing how they have 3 colours (plus a neutral), I personally like `iris` + `foam` + `gold` together (and `text` for the neutral). But please go with whatever you prefer 😌
