### ISSUE TITLE
Matching brackets on same line in Dawn aren't obvious

### ISSUE THREAD

**Issue by briandipalma** [rose-pine/neovim#47]
![image](https://user-images.githubusercontent.com/1597820/145254377-2c11c820-ddea-404a-9fdc-1b4ce575e4c2.png)
Slightly more obvious when on another line (line 5 down `}`):
![image](https://user-images.githubusercontent.com/1597820/145254442-45c62e13-942c-429f-a5b5-a50af0c0a8db.png)

Could probably do with a small tweak darker in both cases maybe?

**Comment by mvllow** [comment]
Thanks for pointing this out. I made the highlight a little darker – we do have one shade darker if necessary 😌

**Comment by briandipalma** [comment]
Thanks for the quick fix, looks much better.
