### ISSUE TITLE
Diff highlighting is hard to read

### ISSUE THREAD

**Issue by RaulCote** [rose-pine/neovim#51]
Hi, the Diff highlighting is not good. I understand the theme goes for a minimal approach but the background should be properly highlighted in redish or greenish way depending on the additions and deletions. The diff area looks kind of broke. It's not really usable, I tend to change to another theme briefly so I can really see easily the changes and reason about them.

As an example, this is tokyonight: 

![image](https://user-images.githubusercontent.com/42467898/146904234-ba7a19ef-053a-4a8d-be4d-80b2c8043bd6.png)

And this is rose-pine:

![image](https://user-images.githubusercontent.com/42467898/146904320-fd617bd0-2da6-481a-a6ee-deb2d7d772ad.png)

It's quite difficult to see because the rose.foam color is already used heavily for other things. I think background colors for the diffs are pretty much needed.

On another hand, terrific work. The theme is lovely, this is the only flaw I see.

**Comment by mvllow** [comment]
Thanks for pointing this out, I've never used any sort of diff inside of neovim. I will attempt to fix the highlighting if I'm able to reproduce but am happy to accept a PR

**Comment by mvllow** [comment]
After playing with the diff feature, I also decided to not change the text highlight and add the highlighted background as suggested. Haven't tested it under too many different scenarios so if anything is still hard to read or could be improved please let me know 😌

**Comment by RaulCote** [comment]
Thanks! The addition/ deletion changes are perfect. But I still think the changes could be much better. 

As you can see on the screenshot below, the changed line is highlighted very strongly on a dark grey. This highlighting is not that important. It should be something very subtle. Almost invisible. The important thing is the text changed itself that in the following example is just the Type of the args:  <T extends WithId ...  

Right now:
![image](https://user-images.githubusercontent.com/42467898/147055013-92b1cb67-3032-472e-9a06-e3a1afc77b47.png)

Other themes examples:

tokyonight: 
![image](https://user-images.githubusercontent.com/42467898/147056505-28606576-2be0-41bc-83b4-52a2c5b5efc6.png)

onedark:
![image](https://user-images.githubusercontent.com/42467898/147056637-1945ffc7-193d-460e-9d90-5550aacf1ce5.png)

sonokai:
![image](https://user-images.githubusercontent.com/42467898/147057176-57c20627-79d6-450a-9ed1-9aabf5b836b0.png)


My idea on how it should look on rose-pine (playing with your blend and highlight_med on DiffChanged and DiffText):
![image](https://user-images.githubusercontent.com/42467898/147056438-613ab393-dbba-4469-9819-d931d0da67e6.png)

**Comment by mvllow** [comment]
happy to keep iterating, i appreciate the great feedback. latest commit makes everything a bit more vibrant
