### ISSUE TITLE
barbar buffer picking

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [rose-pine/neovim#52]
![image](https://user-images.githubusercontent.com/79387351/147802829-e6f2fc1c-3401-4907-bac0-9f29e67f2377.png)
[barbar](https://github.com/romgrk/barbar.nvim) has implemented a buffer-picking option which highlights the key required to select the particular buffer.

the highlight color seems a bit jarring (see image). can this color be changed to be more cohesive with the colorscheme?

**Comment by mvllow** [comment]
appreciate the report – i don't use this personally so please let me know if anything else looks off

**Comment by g-e-o-m-e-t-r-i-c** [comment]
thanks for the early response! appreciate it.
