### ISSUE TITLE
Do not set variant nor background unless explicitly requested

### ISSUE THREAD

**Issue by Slotos** [rose-pine/neovim#55]
In response to setting background option (n)vim reloads colors.
With [init.lua](https://github.com/rose-pine/neovim/blob/main/lua/rose-pine/init.lua#L12) handling of background matching, switching to light background enforces dawn variant, ignoring further background changes.

A straightforward fix would be to remove the code that sets variant and background without user input and update `palette.lua` to factor in `vim.o.background` value when deciding on palette.

As an improvement, I'd like to propose two modes of operation:
- respect background (default) - if variant doesn't match background, use default variant for background
- respect variant - if variant doesn't match background, set matching background

**Comment by mvllow** [comment]
Forgive me if I'm misunderstanding, but I believe things currently behave as such:

* If user sets any variant, that variant would disable any automatic switching
* If user does _not_ set a variant, match background

Please clarify your expected behaviour. It kind of sounds like you are wanting to the variant to switch if you manually set `vim.o.background`?

Appreciate you 😌

**Comment by Slotos** [comment]
Right now, if user doesn't set variant:

- if background is dark, variant is not set and `palette.lua` defaults to `main` palette
- if background is light, variant is set to `dawn`, which ignores any future changes to background option

In combination with (n)vim behaviour of reloading colors on background change this results in a confusing behaviour.
Specifically, if I start with dark background and switch to light, colors switch to `dawn` palette as expected. But then when I switch to light background, `dawn` palette persists even though I didn't set it explicitly.

My basic expectation is for theme to follow background color, unless I set it explicitly.

-------

I would greatly appreciate (and am going to take a shot at implementing) if this scheme would go beyond basic expectation by offering a, what I believe could be a default, mode of operation where it only uses a variant if it matches currently chosen background.

Specifically:
- `main` and `dawn` are implicit
- `moon` is used in place of main if and only if background is dark and variant is explicitly set to `moon`
- Toggle function toggles by setting: `background=light; vim.g.rose_pine_variant=nil`, `background=dark; vim.g.rose_pine_variant=nil`, and `background=dark; vim.g.rose_pine_variant='moon'`

**Comment by mvllow** [comment]
Thanks for explaining, I would gladly look at PR for this functionality – that does sound like a reasonable default

**Comment by mvllow** [comment]
This _should_ be working on the canary branch. There are other changes on the canary branch such as moving all config to lua (currently undocumented)

**Comment by Slotos** [comment]
My apologies for long silence, had a few busy weeks.

Just checked and it works like a charm:
- Switching background reloads theme to a light or the configured dark variant
- Calling `setup` function _doesn't reload colors_, yet on the next load selects the new variant if background color matches
  - _This is the first lua theme I saw do this, which makes for an easy way to set up theme for future selection without employing vim global variables_

👍
