### ISSUE TITLE
Improve non-treesitter support

### ISSUE THREAD

**Issue by mvllow** [rose-pine/neovim#6]
Although treesitter is common amongst neovim users, the native highlight groups should be more consistent.

**Comment by sorachii** [comment]
Hi!

I came across that markdown files are not exactly covered for some reason. I'll attach screenshot tomorrow. What can I do if I'd like to help improve on this?

Best regards

**Comment by mvllow** [comment]
Any additions are welcome and appreciated. If you have questions on _how_ to add something let us know; as far as _what_ to add, that’s up to you and your judgement 😌 

We generally want to avoid non-neutral colours for large blocks of text (eg. markdown paragraphs) but headings, links etc. are all open to be added/changed.

**Comment by sorachii** [comment]
It would be my first neovim theme contribution. I am interested in working on it. Is there any good resource you'd suggest before starting? I am quite busy so it might take me some time to implement it.

**Comment by mvllow** [comment]
Sure thing, you should only need to modify `./lua/rose-pine/theme.lua`. If you look at lines 125-130 (at the time of writing) there are some html groups, eg. `	htmlTag = { fg = p.subtle },`. You could add your markdown highlight groups under those with a similar format.

To find highlight groups to add, open a markdown file in neovim and do `:highlight markdown<Tab>` (tab completing through all available options). You could then do `:highlight markdownBold guifg=#fa8072` to see bold text in a markdown file turn salmon coloured.

Next, add the group to that `theme.lua` file mentioned above, using whatever colours you want in the Rosé Pine palette. For example:

```lua
  ...
  htmlTagName = { fg = p.foam },

  -- This would be your new line
  markdownBold = { fg = p.iris },

  DiagnosticHint = { fg = groups.hint },
  ...
```

Finally, if you want to test locally, update your plugin config to point to your local version of the theme. Using packer:

```lua
-- use('rose-pine/neovim')
use('~/dev/local-theme')
```

A bit much, so please feel free to reach out with any questions. Hope this helps 😌

**Comment by sorachii** [comment]
Wow. I was not expecting this detailed instructions. I really appreciate it!  I am sure this puts me on the right track. 😊

**Comment by sorachii** [comment]
Hi @mvllow!

Tried fidgeting with the markdown highlight groups but for some reason it wont use what I set either on the `:nvim command line` nor what I set in `~/git/rose-pine-markdown-fork/lua/rose-pine/theme.lua`.

On the following theme, gruvbox-material, I can see that nvim uses the highlightgroups I would like to set but when I set it, it won't work.

![2021-11-07 14_24_22-gruvbox-material-markdown](https://user-images.githubusercontent.com/48826429/140647728-fb448fdf-ce9e-427d-84e3-340858574a59.png)


Here you can see nvim with rose-pine on the left, just installed vim without config on the right. When I set highlight colors on regular vim like you showed, it works but not on nvim.
![2021-11-07 14_42_37-markdown-highlights-nvim-vim](https://user-images.githubusercontent.com/48826429/140647730-dac4733d-5de3-4403-b37d-4f817371d566.png)

I am on v0.6.0-dev+518-g1dbbaf89b build. 
[Here](https://github.com/sorachii/rose-pine-markdown-fork/commit/f14f0f162abc7c3e742fb230c66a02ef1d1ac14d) are the highlight changes I tested and would be cool if I can see them work so I can conftinue with more highlights.
Do you have any tips on why it is not working?

**Comment by sorachii** [comment]
Found the issue. For some reason the highlight group in nvim for markdown headers is not markdownH1, instead htmlH1. I'll continue the work. :)

**Comment by sorachii** [comment]
What is a good way to figure out what highlight groups are I am looking for apart from trying out a bunch, then stumbling upon the ones I am looking for?

**Comment by mvllow** [comment]
I would take a look at some other themes. For example, [tokyonight.nvim](https://github.com/folke/tokyonight.nvim/blob/main/lua/tokyonight/theme.lua) has the following:

```lua
    htmlH1 = { fg = c.magenta, style = "bold" },
    htmlH2 = { fg = c.blue, style = "bold" },

    -- mkdHeading = { fg = c.orange, style = "bold" },
    -- mkdCode = { bg = c.terminal_black, fg = c.fg },
    mkdCodeDelimiter = { bg = c.terminal_black, fg = c.fg },
    mkdCodeStart = { fg = c.teal, style = "bold" },
    mkdCodeEnd = { fg = c.teal, style = "bold" },
    -- mkdLink = { fg = c.blue, style = "underline" },

    markdownHeadingDelimiter = { fg = c.orange, style = "bold" },
    markdownCode = { fg = c.teal },
    markdownCodeBlock = { fg = c.teal },
    markdownH1 = { fg = c.magenta, style = "bold" },
    markdownH2 = { fg = c.blue, style = "bold" },
    markdownLinkText = { fg = c.blue, style = "underline" },
```

I _think_ it should be enough to try `:hi markdown<Tab>`, `:hi mkd<Tab>` and `:hi html<Tab>` to see available groups. I wish there was a guide with more exact information, every theme seems to be different.

**Comment by sorachii** [comment]
I think I found a cool solution to get highlight group from under the cursor.
[nvim-treesitter/playground](https://github.com/nvim-treesitter/playground#show-treesitter-and-syntax-highlight-groups-under-the-cursor)

**Comment by sorachii** [comment]
What should I do in order to separate the syntax group of dark/light bg or Regular/Dawn/Night themes?
The same highlight group colors doesn't play well with dark and light themes:

![2021-11-07 21_06_19-light-bad](https://user-images.githubusercontent.com/48826429/140660464-6f0ffcec-c7c9-4bbb-9193-f9174521374a.png)
![2021-11-07 21_09_26-dark-good](https://user-images.githubusercontent.com/48826429/140660466-1ac34023-8cd7-4acb-bec6-1e3f60a4e11b.png)

We could separate the highlight groups by rose-pine variant or background light/dark just like the palette in `lua/rose-pine/palette.lua`. There might be better solution, that is why I am asking you. :)

**Comment by mvllow** [comment]
That should be handled for you by using `p.foam` for example in your theme. So testing locally `mkdListItemLine = { fg = p.foam }` would be similar to `:hi mkdListItemLine guifg=#9ccfd8` for Rosé Pine and `:hi mkdListItemLine guifg=#56949f` for Rosé Pine Dawn. Hope that makes sense 😌

**Comment by sorachii** [comment]
I appreciate your answer.                                                      
                                                                               
I see it handles tones but I was thinking it could be nice to use love, rose,  
gold, iris mainly for the Dawn theme and colder tones like pine, foam, iris for
Regular and Moon themes.                                                       
                                                                               
I am continuing with the tone shifting approach for now, just wanted to share   
this idea.

**Comment by mvllow** [comment]
I would say let's stick to same colours for each variant now but I like your idea of having a tailored experience per variant. May revisit in the future – will need to refactor our other syntax themes to match.
