### ISSUE TITLE
Change in current line highlight

### ISSUE THREAD

**Issue by danymat** [rose-pine/neovim#65]
Hello, it seems that some of the last commits did change the line highlight (in moon theme).

If is a lot stronger than before:

Before:

![Capture d’écran 2022-02-08 à 15 38 38](https://user-images.githubusercontent.com/5306901/153009135-b74bfa26-2f26-4365-86d8-b0d4dbf58965.png)

After: 

![image](https://user-images.githubusercontent.com/5306901/153009185-207f3f9a-044a-4051-a515-b34f92ebc842.png)

Is this part of a ref? If so, I preferred the default behavior.

PS: I really love the new highlights for telescope 💘

**Comment by mvllow** [comment]
I appreciate you and anyone else who points stuff like this out – I am usually testing out changes in a well-lit environment so contrast can seem low in the dark variants but when revisiting them in a dark environment the contrast seems fine.

I'll go ahead and revert the cursorline change; glad you like the telescope highlights 😌
