### ISSUE TITLE
Options are not being applied

### ISSUE THREAD

**Issue by danymat** [rose-pine/neovim#69]
Hello ! 

I just saw that you moved the config to a Lua setup call, however I have some options that are not being applied.

My Lua config:

```lua
		use({
			"rose-pine/neovim",
			as = "rose-pine",
			config = function()
				require("rose-pine").setup({
                    dark_variant = 'moon',
                    bold_vert_split = true,
                    disable_float_background = true,
                    disable_background = true,
                    dim_nc_background = true
                })
				vim.cmd([[ colorscheme rose-pine ]])
			end,
		})
```

I think that all options are not applied except the `dark_variant` option.
Could you take a look ?

**Comment by mvllow** [comment]
hmm, i'm unable to reproduce on my end – would you mind deleting `~/.local/share/nvim/site/pack/packer/start/rose-pine` and running `:PackerSync` again? i had to do a force push yesterday and sometimes that creates issues when updating

**Comment by danymat** [comment]
Still the issue: you can take a look at the background of nvim-cmp, or open a telescope prompt. They seem to still have the backgrounds

**Comment by danymat** [comment]
It seems to still have the issues, but now I got this: Random black appears on some locations:

<img width="429" alt="Capture d’écran 2022-02-14 à 22 31 07" src="https://user-images.githubusercontent.com/5306901/153949748-f2fc08f9-b84e-419c-be16-9144883133c3.png">

**Comment by mvllow** [comment]
is that your cursorline?

**Comment by danymat** [comment]
It is my cursor line on insert mode

**Comment by mvllow** [comment]
that may be a modes.nvim issue, i know we use a blend there most likely using `Normal guibg` which when background is disabled would cause this to be black

if you want to follow #70 the best solution would probably be to eventually override `Normal guibg` to whatever colour you want so it has a value to pull from

**Comment by danymat** [comment]
Right,
However I still face the issue of options not being applied. 
What would you need to reproduce the issue, or have insights ?

**Comment by mvllow** [comment]
could you provide screenshots of what's not being applied? for example, are you attempting to use a transparent background but neovim has a background set still? or are italics visible even though `disable_italics = true`? i've tested every setting on latest nvim nightly (although nvim version shouldn't be relevant)

**Comment by danymat** [comment]
My bad, it seems that dim_nc_background was the culprit. I don't know why I used that ! I recommend adding some explanation in README of what the options are supposed to do, nevertheless.

I'm closing this issue, as it seems to be resolved ! 

However, I'm still concerned about disabling hl for modes.nvim insert mode (Your previous comment was a little bit obscure to me, about changing guibg for Normal hl). But maybe this is only a workaround for a proper support in https://github.com/mvllow/modes.nvim/issues/11

**Comment by mvllow** [comment]
i'll try to better document what i meant in regards to modes.nvim as well as the other options 😌
