### ISSUE TITLE
implement theme overrides

### ISSUE THREAD

**Issue by RaulCote** [rose-pine/neovim#70]
Hello!

As stated on other issues, I do really enjoy this theme and I'm using it daily but I'm still not happy with the diffs. I've been thinking that theme overrides should be implemented as other themes do, it's a missing feature within rose pine. The example I copy below does work but I think your theme is coded very nicely so I just give my tip for you to implement it instead of sending a proper PR:

**theme.lua:**

![image](https://user-images.githubusercontent.com/42467898/153925155-52d3b424-ca84-48cf-9c90-bb52d38c24b8.png)

**config.lua:**

![image](https://user-images.githubusercontent.com/42467898/153925295-b528cab3-04fa-4648-bcfe-986afb87ce89.png)

So then users can make stuff like this on their nvim configs:

![image](https://user-images.githubusercontent.com/42467898/153925423-14303c20-3b95-49e0-9709-2e3290ff2d4d.png)

**Comment by mvllow** [comment]
i'm not against adding overrides, but until i have time to do so – there are undocumented git groups that you can mess with:

```lua
require('rose-pine').setup({
	groups = {
		git_add = 'foam',
		git_change = 'rose',
		git_delete = 'love',
		git_dirty = 'rose',
		git_ignore = 'muted',
		git_merge = 'iris',
		git_rename = 'pine',
		git_stage = 'iris',
		git_text = 'rose',
	}
})
```

please note, `DiffAdd`, `DiffDelete`, and `DiffText` are blended at 50% opacity which cannot be changed at this time

```lua
-- theme.lua code demonstrating blends
DiffAdd = { bg = blend(groups.git_add, p.base, 0.5) },
DiffDelete = { bg = blend(groups.git_delete, p.base, 0.5) },
DiffText = { bg = blend(groups.git_text, p.base, 0.5) },
```

hope this helps until overrides are added 😌

**Comment by RaulCote** [comment]
I did update the theme and I think those groups aren't working. I see all git diffs with black:

![image](https://user-images.githubusercontent.com/42467898/154079066-0bf97f1c-1eef-47ec-b05c-2d02ee7b3948.png)

I didn't check all the code but I didn't see any re-mapping of the groups table to get the proper hex values from the palette. 

As an example:

`DiffText = { bg = blend(groups.git_text, p.base, 0.5) }`

When it should be something like:

`DiffText = { bg = blend(palette[groups.git_text], p.base, 0.5) }`

It could work like that or directly mapping the whole groups table to re-write it the whole groups table before using it on theme.lua.

**Comment by mvllow** [comment]
colours should now show for the diffs – there was a regression that caused the colors to not be applied

**Comment by ndom91** [comment]
Just came here to say that diffs (both `+` and `-` were showing with a black background now). 

Happy to see the update was just waiting for me to pull :grin:
