### ISSUE TITLE
Support toggleterm highlights config

### ISSUE THREAD

**Issue by will** [rose-pine/neovim#76]
A recent patch to toggleterm made it so that, without any custom config, the background would always be dark even if neovim started up with `bg=light` and rose-pine correctly auto went into the light alt.

I was able to work around the problem with the help of the toggleterm author https://github.com/akinsho/toggleterm.nvim/pull/166#issuecomment-1098513458

However, I don't really understand vim theming. I'm happy to keep my manual fixes for toggle term. But also I know rose-pine sets some themes for other plugins. Should (or even can?) rose-pine come with specific settings for toggleterm?

**Comment by mvllow** [comment]
We solved a similar issue with lualine by recommending lazy loading via `event = 'ColorScheme'`. Unfortunately this did not work the same with toggleterm.

As discussed in [this issue](https://github.com/rose-pine/neovim/issues/56) regarding their bufferline plugin, we may be able to export some highlights that the user could apply.

E.g.

```lua
local highlights = require('rose-pine.plugins.toggleterm').highlights

require('toggleterm').setup({
   highlights = highlights
})
```

I have not tried implementing this but that could be a good generic solution 😌 Thanks for bringing this to our attention

**Comment by will** [comment]
Not sure if it matters or helps, but this is what I'm now using for toggleterm's setup()

```lua
  highlights = {
    Normal = { link = "Normal" },
    NormalFloat = { link = "Normal" }, -- also using NormalFloat here makes the border weird
    FloatBorder = { link = "FloatBorder" },
    SignColumn = { link = "SignColumn" },
    StatusLine = { link = "StatusLine" },
    StatusLineNC = { link = "StatusLineNC" },
  },
```

**Comment by mvllow** [comment]
Thank you, that seems to work perfectly
