### ISSUE TITLE
Disable italics does not actually does that

### ISSUE THREAD

**Issue by skopjanecot** [rose-pine/neovim#84]
Hi, thanks for the effort to create this very nice color scheme.
Unfortunatelly, `disable_italics = true` is not doing it's job at the moment :)
<img width="519" alt="Screenshot 2022-07-01 at 03 53 53" src="https://user-images.githubusercontent.com/46635826/176807248-97afc8bf-97cd-498a-a1aa-c5a389fa9402.png">

**Comment by mvllow** [comment]
Oh no! Are you able to temporarily configure Rosé Pine similar to this:

```lua
-- Inside a packer "use"
use({
	'rose-pine/neovim',
	as = 'rose-pine',
	config = function()
		require('rose-pine').setup({ disable_italics = true })
		vim.cmd('colorscheme rose-pine')
	end,
})
```

I'm not able to reproduce but make sure you are setting the colorscheme after setup 😌
