### ISSUE TITLE
Strange highlight on entire blocks

### ISSUE THREAD

**Issue by samtgarson** [rose-pine/neovim#88]
Hey, thanks for the great theme.

I've just installed and I'm getting an odd highlight around entire code blocks/bracket pairs as I move the cursor, which I've not seen in any other theme before:

https://user-images.githubusercontent.com/6242344/180077055-cb18680b-4b43-472a-8ec5-78bbae4ebaa5.mov

I can't find anything about this in any nvim docs—it doesn't seem to be related to `cursorline` or `cursorcolumn` which are the only things using the actual hex code in the theme, as I'm able to turn those on/off as expected.

Any ideas on how to disable this?! I find it really distracting. Thanks 🙌 

Edit: this could be due to background colours mismatching between terminal and vim itself, anyone know how to resolve this?!

**Comment by mvllow** [comment]
You could try disabling the background:

```lua
require('rose-pine').setup({
	disable_background = true,
	disable_float_background = true,
})
```

If you are using Rosé Pine for your terminal please let me know which terminal you are using and I can try to reproduce 😌
