### ISSUE TITLE
Lack of contrast in popups?

### ISSUE THREAD

**Issue by briandipalma** [rose-pine/neovim#89]
Honestly I've no idea if this thing is even called a popup but I notice all these type of popup like windows in Neovim have no contrast so it's hard to tell their bounding rectangle:

![image](https://user-images.githubusercontent.com/1597820/180750983-31075b78-1bb2-4f7f-92cf-605d970bd99a.png)

Compare that to:

![image](https://user-images.githubusercontent.com/6705160/177617680-d62caf26-f253-4ace-ab57-4b590595adca.png)

**Comment by mvllow** [comment]
I agree this could probably be better as our `surface` colour. I'll try to find which highlight groups are responsible for this and see how it looks with higher contrast :)

**Comment by mvllow** [comment]
Sorry this took a me a bit to test – I recently moved my personal config to using Mason, however, and the floating window does have a different background.

<img width="705" alt="Screenshot 2022-08-16 at 20 20 05" src="https://user-images.githubusercontent.com/1474821/185007094-827f4f2f-2177-4b55-a4c6-8ed24c2e1e84.png">

**Comment by briandipalma** [comment]
Odd:
![image](https://user-images.githubusercontent.com/1597820/185093264-4d3a1fa6-0996-47fc-9325-46873a83c104.png)

No idea what's going on but it's not the theme so I'll close this issue, thanks for looking into it though.
