### ISSUE TITLE
bufferline breaking changes

### ISSUE THREAD

**Issue by will** [rose-pine/neovim#91]
https://github.com/akinsho/bufferline.nvim/pull/497 did a breaking change in the way hilights are done. I've been trying to poke around at getting things working again but no luck yet to report. Especially problematic is switching between light and dark and back

**Comment by AnthonyK213** [comment]
Same here. And i've made sure that the colorscheme is loaded before bufferline

**Comment by mvllow** [comment]
Hmm, the only bufferline support we have is in https://github.com/rose-pine/neovim/blob/main/lua/rose-pine/plugins/bufferline.lua:

```lua
	buffer_visible = {
		guifg = p.subtle,
		guibg = p.base,
	},
	buffer_selected = {
		guifg = p.text,
		guibg = p.surface,
		gui = 'bold,italic',
	},
```

If you are using that, or a variation of that, perhaps this change would fix it:

```diff
	buffer_visible = {
-		guifg = p.subtle,
-		guibg = p.base,
+		fg = p.subtle,
+		bg = p.base,
	},
	buffer_selected = {
-		fg = p.text,
-		bg = p.surface,
+		fg = p.text,
+		bg = p.surface,
		gui = 'bold,italic',
	},
```

Please let me know if I'm misunderstanding, I don't personally use bufferline.

**Comment by will** [comment]
I wasn't actauly using that file in my setup before. Everything just worked out of the box (both light&dark and swapping between the two while running) without any custom setup for bufferine. 

I've since tried
  * using the file as described in the wiki
  * editing it to be `fg` instead of `guifg` 
  * link to another group that rose-pine creates

With no luck yet. I'll keep poking at it

**Comment by will** [comment]
> And i've made sure that the colorscheme is loaded before bufferline

Me too, 100% sure that it's before by not even using the packer setup stuff, manually having rose-pine first, then `colorscheme` then buffer line. Still bufferline shows up with the dark colors from rose-pine even when starting in light mode. 

I have found out though that if I call the bufferline setup function again manually well after everything is loaded, it'll then use the light theme colors.

Then switching to dark mode with `set background=dark`, bufferline keeps the light mode colors. 

I have one last thing I want to try, but figured I should share progress

**Comment by mvllow** [comment]
https://github.com/akinsho/bufferline.nvim/issues/512 seems related maybe? I wonder if you're able to call bufferline setup multiple times (e.g. using an autocmd when background changes) or if that messes things up

**Comment by will** [comment]
That was actually the thing I wanted to try. I've also thought maybe setting all of these groups manually might work, but I'm trying to figure out a programmatic way to get the list and what colors it happened to pick but maybe it'd be faster to just power through it manually 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/1973/185007902-fd18b8f6-6cfd-4427-9ea4-be284272fc1a.png">

**Comment by will** [comment]
So far, recalling setup in the autocommand seems to be working, but I'll keep my eye out for that causing problems

```lua
local use = require("util.packer").use
use "moll/vim-bbye"
use "akinsho/bufferline.nvim"

local config = function()
  require("bufferline").setup {
    options = {
      numbers = "none", -- | "ordinal" | "buffer_id" | "both" | function({ ordinal, id, lower, raise }): string
      close_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
      right_mouse_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
      left_mouse_command = "buffer %d", -- can be a string | function, see "Mouse actions"
      indicator_icon = "▎",
      buffer_close_icon = "",
      modified_icon = "●",
      close_icon = "",
      left_trunc_marker = "",
      right_trunc_marker = "",
      max_name_length = 30,
      max_prefix_length = 30, -- prefix used when a buffer is de-duplicated
      tab_size = 21,
      diagnostics = false, -- | "nvim_lsp" | "coc",
      diagnostics_update_in_insert = false,
      offsets = { { filetype = "NvimTree", text = "", padding = 1 } },
      show_buffer_icons = true,
      show_buffer_close_icons = true,
      show_close_icon = true,
      show_tab_indicators = true,
      persist_buffer_sort = true, -- whether or not custom sorted buffers should persist
      separator_style = "thin", -- | "thick" | "thin" | { 'any', 'any' },
      enforce_regular_tabs = true,
      always_show_bufferline = true,
    },
  }
end

config()
vim.api.nvim_create_autocmd("OptionSet", {
  pattern ="background",
  callback = config,
  group = vim.api.nvim_create_augroup("bufferline color", { clear = true }),
})
```

**Comment by will** [comment]
I had it working then it broke again, and now it's always be on exactly the wrong color (like always light bar in dark mode and dark bar in light mode).

So I give up. Every time I launch neovim I start fiddling with it and don’t get much real work done haha. I'm going to just stick on bufferline tag `v2.5.1` until that breaks with some neovim change or something and I'm forced to update.

**Comment by AnthonyK213** [comment]
it has been fixed [523](https://github.com/akinsho/bufferline.nvim/pull/523)

**Comment by will** [comment]
Thanks for keeping track of it @AnthonyK213 and posting here! Everything is great now. I'm going to close it.
