### ISSUE TITLE
`EndOfBuffer` highlight group override not taking precedence

### ISSUE THREAD

**Issue by theteachr** [rose-pine/neovim#94]
After running `PackerySync`, and it notifying about the breaking change, my override of `EndOfBuffer` highlight group's `fg` is not respected, where they are white, instead of the said color.

![image](https://user-images.githubusercontent.com/64728420/190840897-c4399244-386f-4737-bb9d-68be2250c291.png)

**Comment by mvllow** [comment]
1. Does your ColorColumn override work?
2. Could you try NonText instead of EndOfBuffer?

Appreciate the report :)

**Comment by theteachr** [comment]
`NonText` works. Did something change in the update? Because I was able to control the same element with the `EndOfBuffer`.

**Comment by mvllow** [comment]
Had to double check but our highlight function hasn't changed, so my best guess is perhaps another plugin update started theming `EndOfBuffer` or something in neovim core. Glad `NonText` works though :)
