### ISSUE TITLE
feature: Expose each variant as its own colorscheme

### ISSUE THREAD

**Issue by lukepighetti** [rose-pine/neovim#98]
Can't get the moon variant to work, is that supported by this plugin?

```
...
Plug 'rose-pine/neovim', {'as': 'rose-pine', 'branch': 'main' }
...

colorscheme rose-pine-moon
```

**Comment by mvllow** [comment]
Absolutely! We have options mentioned in the readme with lua examples. To use them in vimscript:

```vimscript
lua << EOF
require('rose-pine').setup({
	--- @usage 'main' | 'moon'
	dark_variant = 'moon'
})
EOF

colorscheme rose-pine
```

Be sure that colorscheme is set _after_ the setup :)

**Comment by lukepighetti** [comment]
we can't expose multiple themes like tokyonight? https://github.com/folke/tokyonight.nvim#-usage

**Comment by mvllow** [comment]
I'd happily accept a PR that added that functionality. Not a huge priority for me, though.

**Comment by mvllow** [comment]
Added in #114 (canary branch). Will be merged to main soon :)

**Comment by briandipalma** [comment]
Thanks, this change seems to have fixed the flickering from dark them to dawn when launching Neovim and the gitcommit messages are now also in dawn, for some reason before they were in dark which was jarring!
